### ISSUE TITLE
Keyvault: sku.name should be case sensitive against the defined enum

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#10082]
KeyVault API (2016-10-01) allows case-insensitive `Sku.name`, which invalidates the enums defined in swagger.
We should change that to case-sensitive so as to exactly match the definition in,swagger.

**Comment by sebansal** [comment]
Hey @jlichwa can you help triage this issue?

**Comment by jlichwa** [comment]
We can't change and different API's today using different case between our APIs and Portal. It will be breaking change - we can't change it.

**Comment by mikhailshilkov** [comment]
@jlichwa Will you fix that in newer API versions?

**Comment by eliavVivid** [comment]
still encountering this in 2026. either change the spec so it says enums are not case sensitive or fix the api response. the api returns 'Standard' instead of 'standard'(enum specifies 'standard', [see](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/KeyVault/stable/2026-02-01/openapi.json#L5576) )
