### ISSUE TITLE
Get SQL VM fails at 7/15

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10144]
We get customer issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7747
Get SQL VM fails this morning at 7/15:

Request: 
GET /subscriptions/.../resourceGroups/yupsqlvm/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/yupsqlvm?%24expand=%2A&api-version=2017-03-01-preview HTTP/1.1

Response:
{
    "error": {
        "code": "InternalServerError",
        "message": "An unexpected error occured while processing the request. Tracking ID: '0970fdc6-1fb8-4ec4-a4f8-f858bff68eda'"
    }
}

**Comment by fnocera** [comment]
We have been trying to trace down this issue for two days. Initially we thought it was the terraform provider https://github.com/terraform-providers/terraform-provider-azurerm/issues/7747 or the go sdk https://github.com/Azure/azure-sdk-for-go/issues/11575 but on reflection now it must be the API because we are getting the same behavior in spite of the go skd version. 

We have tried accessing the same provisioned resource using the [API call](https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/get#code-try-0) you can submit via the docs and it is successful so it is very confusing. I have only tested out the `api-version=2017-03-01-preview` on the website so I do not know if the issue could be with another version or with the auth process? 

Please help us get this resolved asap as our customer is not able to provision environments without this working effectively. 

cc @yutyang @briangottfried

**Comment by fnocera** [comment]
Cross posting from https://github.com/Azure/azure-sdk-for-go/issues/11575 as this issue seems to be related to the API spec. 

We have continued our investigation on this to understand the exact API calls being made by the go sdk. This is the exact GET request being made 
``` 
GET /subscriptions/<subscription>/resourceGroups/rpt-db-yutyang5/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/rpt-db-yutyang5?%24expand=%2A&api-version=2017-03-01-preview
```
The "expand" query params are being incorrectly encoded as `%24expand=` instead of `$expand=`. Running the above API call directly returns a 500 error `{    "error": {        "code": "InternalServerError",        "message": "An unexpected error occured while processing the request. Tracking ID: 'd0e68047-b036-4f32-b1c3-2743af943759'"    }}`

Additionally the specs state that `$expand=` should work correctly, however we also get a 500 error when using `$expand`, removing the `$` fixes the problem and we get a 200 OK with proper payload. 

This looks like a bug in both the go sdk and the API spec itself. Please let me know your thoughts - it is urgent we get this addressed. 

[logs.txt](https://github.com/Azure/azure-sdk-for-go/files/4925945/logs.txt)

cc @yutyang @briangottfried

**Comment by marioanton** [comment]
Issue still on 2.17 version of azurerm so must be the api for sure. 
Currently happening to me and recently created it successfully but now is failing.

**Comment by fnocera** [comment]
@marioanton it is also not working with the azurerm version 2.11 and 2.10 so seems like a possible service problem perhaps?

**Comment by marioanton** [comment]
Any progress on this one MS?

**Comment by marioanton** [comment]
Issue sorted for me now 👍

**Comment by yupwei68** [comment]
Thanks, this has been fixed.
