### ISSUE TITLE
OS Disk Caching for VM/VMSS OSProfile should not support None

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1044]
According to the Compute team, VM/VMSS OS disks should not support a caching type value of None. Currently both OS and data disks using the same CachingType enum, which has three values: "None", "ReadWrite" and "ReadOnly". This should be split into two enums and the OSDiskCachingType enum should only support "ReadWrite" and "ReadOnly".

**Comment by Drewm3** [comment]
The documentation should indicate that the value of None for the OS disk will be interpreted as "ReadOnly". We decided against actually changing the API to fail if None is specified for the OS disk because that would be a breaking change to some, and we didn't want to introduce a breaking change that was not completely required.

**Comment by kirthik** [comment]
@tjprescott  - Closing this issue based on @Drewm3 comments. Please feel free to re-open if you have any concerns over the decision made.
