### ISSUE TITLE
GET SQL VM fails when the vm is not in running state

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10608]
We get reported issue from https://github.com/terraform-providers/terraform-provider-azurerm/issues/8249.

When we get the SQLVM and the vm is not in running state, we'll get the error:
autorest/azure: Service returned an error. Status=400 Code="VmNotRunning" Message="The VM: /subscriptions/.../resourceGroups/acctestRG-mssql-YUP/providers/Microsoft.Compute/virtualMachines/acctest-VM-YUP is not in running state."

But we could get the vm when it's not in running state. 

Because Terraform will always get the sql vm to compare its resource state with the customer's configuration. That means if the vm is not in running state, we could not manipulate the sql vm.

**Comment by NivedhaChellam** [comment]
[Get SQL Vm](https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/get) call 

1. **With Expand call :** will return the **VmNotRunning** code, If you are doing a expand call like `GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/{sqlVirtualMachineName}?$expand={$expand}&api-version=2017-03-01-preview`, since the VM is not running, it will not be able to read the properties. 

1. **Without Expand call** :will return the vm properties like Id, location and type without erroring out

**Comment by yupwei68** [comment]
Hi @NivedhaChellam Thanks for that. May I ask if there an api for checking if the vm is running?

**Comment by NivedhaChellam** [comment]
You would be able to get the VM running status Without Expand.

**Comment by yupwei68** [comment]
Thanks
