### ISSUE TITLE
ServiceBus queues with virtual path in name

### ISSUE THREAD

**Issue by xtomas** [Azure/azure-rest-api-specs#1082]
When queue's name property contains slash (virtual path), rest api GET call for this queue always fails.

```powershell
 Get-AzureRmResource -ResourceName "mynamespace/desk/incoming" -ResourceType Microsoft.ServiceBus/namespaces/queues -ResourceGroupName Default-ServiceBus-WestEurope -ApiVersion 2015-08-01
```
```
Get-AzureRmResource : NotFound : The requested resource desk does not exist.
At line:1 char:1
+ Get-AzureRmResource -ResourceName "mynamespace/desk/incoming" -Reso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : NotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

Related problem is non functional queue detail in Azure portal and non functional servicebus templating.

Problem is easy reproducable:
1. create queue with name **desk/incoming**
2. in azure portal open blade for this queue detail, or use Get-AzureRmResource to call rest api

**Comment by xtomas** [comment]
Same problem occurs when calling rest api for topics with virtual path in name: mynamespace/desk/incomingtopic

**Comment by salameer** [comment]
Hi @dsouzaarun ,

Can you kindly take a look here or assign it to the right person to review?

Thanks,

Samer

**Comment by dsouzaarun** [comment]
The issue is with the Azure RM, or to be more accurate, how it expects the URI for a resource to be structured. It expects pairs with slash used as a delimiter. See [this](https://blogs.msdn.microsoft.com/servicebus/2017/06/21/azure-service-bus-azure-resource-manager-and-this-character/) blog post that explains the issue with Azure RM.

[ServiceBus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer) on the other hand uses NamespaceManager which doesn't have the same expectation as ARM has and can support slashes in the entity names.

**Comment by xtomas** [comment]
Thanks to all for help :)
Currently '~' works instead of '/' so for example in powershell I can use desk~incoming for all operations.
