### ISSUE TITLE
sku of key vault created by portal does not follow the enum defined in swagger

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-rest-api-specs#10943]
recently, the sku of key vault created by portal becomes "Standard", however the sku defined in all swaggers, such as https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview/keyvault.json, the sku name should be `standard` or `premium`.
The case does not match

**Comment by sebansal** [comment]
@jlichwa is reviewing and will make the changes

**Comment by sebansal** [comment]
The value is not case-sensitive, so we would not be making any changes as of now.

**Comment by mikhailshilkov** [comment]
@sebansal But this value is marked as `modelAsString: false` which means client SDKs model it as enums of the incorrect casing. This leads to problems like https://github.com/pulumi/pulumi-azure-nextgen/issues/294 where spurious diffs are shown because of casing mismatch in API request vs. response.

Why not change the swagger to match the API behavior, at least in newer API versions?

**Comment by jlichwa** [comment]
@mikhailshilkov  "SDKs model it as enums of the incorrect casing" - any case is allowed, so not sure how it will model it as incorrect. We want SDK to model that as enum, so it is easier for customer to pass value to our service.

**Comment by mikhailshilkov** [comment]
I guess my point is that the Open API spec does not reflect the service behavior. At least, it looks wrong to me to receive "Standard" from the service when the API describes the strict enum in a different casing.

> Any parameter in Key Vault service is not case sensitive today

Where in the Open API spec is this specified?

**Comment by JeffreyRichter** [comment]
Here's what I suggest: change the swagger so that, for this enum, modelAsString is set to true. This will break many SDKs but you're probably going to break them in the future anyway is you ever add or remove a SKU. And then, document that clients should do a case-insensitive comparison on these strings.
