### ISSUE TITLE
CosmosDB Compound Index Sort Order returns incorrect case for `CompositePathSortOrder` in `Get`

### ISSUE THREAD

**Issue by jackofallops** [Azure/azure-rest-api-specs#11222]
API Version: 2020-04-01

Line Reference: https://github.com/Azure/azure-rest-api-specs/blob/d43b10e044e9e12e1f53a3cc2a9d3d9f01b08d90/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L7062-L7069

The API call returns `descending` or `ascending`, which does not match the Enum values of `Descending` and `Ascending` respectively, resulting in the need to add additional comparison / conversion code that should not be necessary.

**Comment by MehaKaushik** [comment]
Thanks for reporting this, we are investigating it.

**Comment by MehaKaushik** [comment]
Hi @jackofallops Many thanks for reporting this. We have found out that our service is intended to return the lower case values, our swagger is wrongly documented. The same issue holds for IndexingMode (related issue https://github.com/Azure/azure-sdk-for-go/issues/6603)
Since changing the enum value in a stable version is considered a breaking change, we will take up this correction in our next API version. 

I will keep this issue open and track it here until the next apiVersion is released.

**Comment by MehaKaushik** [comment]
Just to update the fix will be released as a part of our upcoming apiVersion 2020-01-15
