### ISSUE TITLE
rest api issue of key vault managed hsm

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-rest-api-specs#11419]
using api-version: 2020-04-01-preview

Q1: why sku.family is a required field?
Q2: when creating with field "EnablePurgeProtection= false", and then we update it to "true". Rest api will success, but the field in the response is still false. It didn't be changed.
Q3: SoftDeleteRetentionInDays could not be updated, is it by design?

**Comment by erich-wang** [comment]
Could keyvault team take a look?

**Comment by sebansal** [comment]
Adding @amitbapat

**Comment by sebansal** [comment]
Ping @amitbapat

**Comment by amitbapat** [comment]
Q1: why sku.family is a required field?
This is an expensive SKU. While there is only one SKU right now, there will be more in future. Setting a default today will cause problems in future.

Q2: when creating with field "EnablePurgeProtection= false", and then we update it to "true". Rest api will success, but the field in the response is still false. It didn't be changed.
Q3: SoftDeleteRetentionInDays could not be updated, is it by design?
Control plane (Management plane) currently does not fully support the whole soft-delete/purge-protection feature including configurable retention period. By general availability we expect to have parity with vaults, in behavior for this feature.

**Comment by amitbapat** [comment]
#please-close
