### ISSUE TITLE
Azure Virtual Machine name allowed characters

### ISSUE THREAD

**Issue by sachin-laddha** [Azure/azure-rest-api-specs#13271]
As per Azure resource naming document 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcompute
a virtual machine name cannot have underscore ( _ ) character in it. This seems to be blocked from Portal but using API (PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}?api-version=2020-12-01)  I could create a VM with underscore character in its name.

Please help me understand what exact set of characters are not allowed in VM name.

**Comment by Drewm3** [comment]
Hi @sachin-laddha, I believe this behavior is blocked in the portal because it uses a single name for both the Azure Resource Manager resource and the computerName in the guest OS on the VM. So the behavior you are seeing is as expected.

However, it does look like there is a broken link in the API documentation for computeName. @avirishuv, could you please update the link in the API documentation to refer to the appropriate page to describe the allowed strings for computerName in the following docs: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#osprofile

**Comment by sachin-laddha** [comment]
Went through above link, it specifies the limit on VM name but does not have any information for VM names. 
Also the link given in above article is broken.

It would really help if someone can give us a list of characters that are NOT allowed in VM name. 
I have raised this issue with MSFT support almost a week back but still no conclusion.

**Comment by sachin-laddha** [comment]
Can someone reply please

**Comment by avirishuv** [comment]
hi @sachin-laddha we'll updating the link for the ComputeName description in this doc https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#osprofile. 

In the meantime, here is the correct link, please let us know if you have further questions. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

**Comment by avirishuv** [comment]
The docs have been updated with the correct link: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update#osprofile

Closing this issue, please feel free to reopen if you have additional questions on this topic.
