### ISSUE TITLE
Compute: swagger definition error

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#13742]
In https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L11072-L11074, a property is defined as:
![image](https://user-images.githubusercontent.com/40835867/113112092-662ec900-923b-11eb-89cd-ff1e99d2c914.png)
The definition of object is wrong. It's defined as object, so there should be a sub-field `properties` which can contains sub-properties. Also，is it an empty object in service side ?

**Comment by Drewm3** [comment]
@srvar, it looks like you had the last commit on this swagger file. Could you please investigate this error?

**Comment by srvar** [comment]
I did not make that change.

**Comment by Drewm3** [comment]
@Sandido, could you take a look at this. It looks like the issue must have been introduced when the 2020-12-01 version of the Swagger file was initially created.

**Comment by Sandido** [comment]
Hi @dw511214992 , @Drewm3 ,  

This swagger definition for the VirtualMachineScaleSetExtensionProperties.setting property has been present since we started using swagger definitions in 2015. 
A swagger property that is just a generic object without properties accepts inputs formatted as JSON. 

The VMSS Extension is agnostic of schemas. The schema is defined by the user in this Setting or ProtectedSetting property via the provided json. 
It takes arbitrary JSON - e.g., CustomScript config might look like:
{
"filesToDownload": [<url1>, <url2>],
"commandToExecute": "powershell <downloadedscript>.ps1" 
}

Please see this page for more info: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#extension-schema
