### ISSUE TITLE
Microsoft.EventHub/namespaces missing read-only "status" property definition

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#13984]
A GET on a namespace resource returns a property named "status", but it is not defined in the swagger spec here:
https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/namespaces-preview.json#L612-L666

Originally raised under https://github.com/Azure/bicep/issues/2297

**Comment by Saglodha** [comment]
@anthony-c-martin , closing this issue since we have status added to the swagger spec in latest api-version : https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/namespaces-preview.json, please feel free to reach out in case of additional queries.
