### ISSUE TITLE
[Insights] ScaleCapacity values are strings?

### ISSUE THREAD

**Issue by whiskeyjay** [Azure/azure-rest-api-specs#1413]
Not sure if this is a bug or feature...

The ScaleCapacity has three properties "minimum", "maximum" and "default". While the descriptions of these properties says "the number of instances", they are all currently defined as strings.

Is there a specific reason to use string instead integer here?

https://github.com/Azure/azure-rest-api-specs/blob/current/specification/monitor/resource-manager/microsoft.insights/2015-04-01/autoscale_API.json#L872

**Comment by gucalder** [comment]
This should be labeled as Monitor instead of Insights. Insights is deprecated.
In fact, the values were intentionally left as strings thinking that, in the future, we might have some other specs for ScaleCapacity that are not expressed numerically.
That said, currently, the values could be specified as numbers.

**Comment by asheniam** [comment]
In the future, autoscale engine may add support for other types of scaling (such as vertical scaling) where the values are not instance count numbers.
