### ISSUE TITLE
Add Cognitive Services Kind Enum

### ISSUE THREAD

**Issue by jongio** [Azure/azure-rest-api-specs#14668]
Right now when you define a resource in bicep you do not get intellisense for kind

![image](https://user-images.githubusercontent.com/2163001/120718227-cf21ff80-c47d-11eb-8650-a67fd7ebdadf.png)

Let's provide help the user by providing them a list of kind options.

azsdke2e
azsdke2e2

**Comment by yangyuan** [comment]
As explained via Teams, due to the nature of Cognitive Services accounts. We dont define Sku and Kind as Enum.
Every region has it's own available Skus/Kinds and combinations. Defining them as enum will cause confusing.
Meanwhile, both Sku/Kind need the flexibility to add and delete and the list doesn't sync with API versions. If we define them as enum we will need a lot of breaking changes.
Both CLI and PowerShell have commends to retrieve available Skus and Kinds, the list is dynamic generated according to subscription and region availability.
