### ISSUE TITLE
Add Cognitive Services SKU Enum

### ISSUE THREAD

**Issue by jongio** [Azure/azure-rest-api-specs#14667]
Right now when you define a resource in bicep you do not get intellisense for sku

![image](https://user-images.githubusercontent.com/2163001/120717946-502cc700-c47d-11eb-8e78-2dc721623b8f.png)

Let's add support for that in the swagger to assist the user in selecting a sku, even if there only is one option, such as 'S'

azsdke2e
azsdke2e2

**Comment by yangyuan** [comment]
As explained via Teams, due to the nature of Cognitive Services accounts. We dont define Sku and Kind as Enum.
Every region has it's own available Skus/Kinds and combinations. Defining them as enum will cause confusing.
Meanwhile, both Sku/Kind need the flexibility to add and delete and the list doesn't sync with API versions. If we define them as enum we will need a lot of breaking changes.
Both CLI and PowerShell have commends to retrieve available Skus and Kinds, the list is dynamic generated according to subscription and region availability.
