### ISSUE TITLE
Key Vault’s properties.tenantId should accept “adfs”

### ISSUE THREAD

**Issue by sadasant** [Azure/azure-rest-api-specs#15108]
Hello team!

The swagger for Azure Key Vault specifies that the `tenantId` property can only be a `uuid` (an example can be found here: [source link](https://github.com/Azure/azure-rest-api-specs/blob/c234651f2885c07ff4a77e50c883145949fda5fa/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview/keyvault.json#L1078-L1082). However, non-uuids exist, such as `adfs`.

We’ve got a customer asking about this issue in one of our packages: https://github.com/Azure/ms-rest-nodeauth/issues/132

**Comment by sadasant** [comment]
cc: @TheOnlyWei 

Once this issue is resolved, we will be able to generate new @azure/arm-keyvault-* clients with the fix included.

**Comment by TheOnlyWei** [comment]
@sadasant I believe the UUID enforicement for keyvault API makes sense. I just don't understand why we are passing "adfs" as tenant Id for the login. Who do we contact to request a feature to allow tenant UUID for the login as well?

Link for login sample:
https://github.com/Azure-Samples/hybrid-keyvault-nodejs-create-secret/blob/5c6160a5ecb42198efc5b7ece929a3418192eb7f/index.js#L103

**Comment by AshokCMSFT** [comment]
Cloud TenantIDs are always UUIDs. ADFS is not supported by Azure Key Vault directly for authentication

**Comment by TheOnlyWei** [comment]
@AshokCMSFT I am talking about inconsistency in ADFS environment authentication. I know it works as UUID in AAD environment.

**Comment by mancyc** [comment]
Not really a 'bug', because the workaround is to use the tenantID as UUID for ADFS environment. 
I agree it is not a great user-experience, bit the inconsistency between AAD/ADFS authentication and why ADFS specifically requires "adfs" appended to the authority is something that needs to be addressed by ADAL/MSAL. KeyVault doesn't own this piece of auth flow.

**Comment by sadasant** [comment]
I don’t think this is specific to the ADAL/MSAL team. They say they specifically don’t differentiate by either case, they treat Azure AD and ADFS authentications in the same way. For ADAL/MSAL, “adfs” is a valid tenant that they send through.

This is really just a feature of Azure https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-single-adfs-multitenant-federation but perhaps I’m missing something.

If this is just a feature of Azure, why not have it on the specs? That tenant ID can be either a UUID or `adfs`?

**Comment by sadasant** [comment]
After some back and forward, this is clearer to me:
So, the underlying issue that @TheOnlyWei is having is that they’re trying to use the Key Vault management client to create a policy in the ADFS environment. ADFS environments don’t actually have tenant IDs, and since the Key Vault management client only works with UUID tenant IDs, this means that the Key Vault service does not support creating policies in the ADFS environment. Is that correct?

cc: @mancyc , @AshokCMSFT

**Comment by TheOnlyWei** [comment]
@sadasant That is correct in that ADAL login used in the sample code linked above uses "adfs" as tenant Id and Key Vault creation uses UUID of tenant Id. ADFS environments do have a tenant Id, but the issue here is inconsistent convention. If we are to accept "adfs" as tenant Id in several SDKs, then it doesn't make sense to not accept it for Key Vault, and vice versa, if we only accept UUID as tenant Id in Key Vault, it doesn't make sense why we even need to use "adfs".

Currently you can work around this conflict by using UUID tenant Id for Key Vault creation, but you must enter "adfs" for login into Azure Stack environment. Which is confusing for the user.

**Comment by sadasant** [comment]
Right, but this is not a bug on the the SDK clients, nor a bug on the rest specs. This is really a feature request for the Key Vault service to support “adfs” tenants in their access policy API.

**Comment by TheOnlyWei** [comment]
Part of this is to also spread awareness of the different interpretations of tenant Id used by SDKs and RPs so as to have consistency in user experience because the SDK teams do not test their code on Azure Stack environments. If this is expected behavior after your investigations and is consistent with Azure, then we can leave this issue for now.

**Comment by sadasant** [comment]
@AshokCMSFT , @mancyc please help us with a statement when you find some time 🙏

**Comment by mancyc** [comment]
KeyVault does support access policies on ADFS in Stack. User should use tenantId from Stack environment. 
I don't think we can/should skip the tenantId here, because our access policy API expects it.
