### ISSUE TITLE
Promote semantic validator to not allowing failures.

### ISSUE THREAD

**Issue by olydis** [Azure/azure-rest-api-specs#1536]
same applies to private repo

**Comment by olydis** [comment]
@salameer concerns?

**Comment by olydis** [comment]
@olydis defer until after Ignite

**Comment by veronicagg** [comment]
@olydis I don't think we can move forward with this yet. If we look at this job: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/279757646 which runs semantic validator on the whole repo, we see that there are still specs not complying with the validation. I don't think we've worked/engaged with these teams much yet on those (and the impact it may have on their specs/SDKs).
In my opinion, this is not an issue with false positives, these are actual errors that would need to be fixed by teams and we want to make sure we engage with them before we turned them into blockers.

**Comment by veronicagg** [comment]
@kirthik please notify teams we'll be turning this on.

**Comment by veronicagg** [comment]
@amarzavery - FYI
