### ISSUE TITLE
[EventHub Schema Registry] REST API Review

### ISSUE THREAD

**Issue by nickghardwick** [Azure/azure-rest-api-specs#15858]
Swagger PR: [15855](https://github.com/Azure/azure-rest-api-specs/pull/15855)

**Comment by markweitzel** [comment]
# API Stewardship Review Board Meeting 7-Sept-21

* There are a number of questions around how a user would discover/get the collection of schemas.
* Individual schema IDs are passed with the event--then the GET can be used. 
* Why doesn't the swagger version match the folder version?  The folder has -preview.
* What happens if someone creates a group called `schemas` with a schema called `schemas`? How do you resolve your routes
* Why is everything coming back headers?
* Is your POST an Upsert?  I can't understand why the doc comment is saying "Get ID for existing schema?
* Where is the API for the version? We do not want to have "hidden APIs." This should be added. 


[C# Examples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/schemaregistry/Azure.Data.SchemaRegistry#examples)

**Comment by nickghardwick** [comment]
Re: Changing Schema/Serialization Type to Content Type in headers:
One thing we can do that wasn't explicitly brought up in the meeting was to have our Content-Type return a known type, such as `application/json` but include an optional parameter to specify the exact type of schema that is being used. For example, an Avro schema is constructed with JSON, so the returned Content-Type would be something like `application/json;serialization=avro`.
Is this an option that makes sense to implement while keeping AutoREST happy? I believe @johanste and @mikekistler were looking into AutoREST compatibility.
