### ISSUE TITLE
[Speaker Recognition] V3.0 GA swagger files

### ISSUE THREAD

**Issue by HeidiHanZhang** [Azure/azure-rest-api-specs#15912]
This is for submitting an updated version of Speaker Recognition swagger files from Preview (V2.0) to GA (V3.0). According to Azure REST API Stewardship guideline, I created this issue for just tracking all the work related to this PR.

PR link is here: #15685

**Comment by markweitzel** [comment]
# API Stewardship Board Review / Discussion 9-Sept-2021

Minor changes between 2.0 (preview) and 3.0. 
* Since this is a major version revision, it would be good to move to our date based versioning. See our [Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#api-versioning).
* There are considerations about POST being idempotent. 
  *  We should look at the retry-able request 
* Change the error codes from the HTTP status name to contextual things (i.e., "MissingLocale" instead of "InvalidRequest")
* See the [guidance](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#collections) on use of "top" and "nextlink" 
*
