### ISSUE TITLE
[Synapse - Run Notebook] REST API Review for Run notebook - newly added API 

### ISSUE THREAD

**Issue by DJrocks999** [Azure/azure-rest-api-specs#16011]
We have recently added new feature named as “RunNotebook”. We have implemented four different APIs under preview version “2021-06-01-preview”. 
We have reused Notebook.Json entity while modeling our API response. All other files (total 5 – including 4 examples) are newly constructed. 
I see few failures under breaking change check which I feel can be ignored.

**Comment by markweitzel** [comment]
## API Stewardship 22-Sept-2021

Instead of PATCH use PUT.
PUT /runNotebookApi/versions/{version}/run/{id}

See https://aka.ms/azapi/guidelines#api-versioning for our preferred way to provide the api-version

API structure should be: PUT /notebooks/{notebook}/runs/{runid}

See [Versioning](https://www.youtube.com/watch?v=bG984_L6dS0&list=PL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65&index=14 )
for more about how to version Azure services

[Link to recording]()
<sup>Note: Internal MS link</sup>
