### ISSUE TITLE
[Communication Services - NetworkTraversal] API Stewardship Review

### ISSUE THREAD

**Issue by jorgegarchirota** [Azure/azure-rest-api-specs#16755]
Review with the Azure Board.

Key contact: anpea@microsoft.com

[Swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/NetworkTraversal/preview/2021-10-08-preview/CommunicationNetworkTraversal.json)

Scenarios:
 - Several object renames (e.g. "Turn" to "Relay" and "TurnServer" to "IceServer")
 - Path replacement from "/turn/{​id}​/:issueCredentials" to "/networktraversal/:issueRelayConfiguration" 
 - Adds a CommunicationRelayConfigurationRequest, making the identity optional - Adds a `RouteType` to IceServers to be requested

**Comment by markweitzel** [comment]
# API Stewardship Rewview 18-Oct-21

@ajpeacock0 & @jorgegarchirota all looks good. Minor stuff to fix...
* Parameter should have a description. (line 26)
* The body parameter is not marked as required. (line 26)
* Error response should contain a x-ms-error-code header. (line 41)

**Comment by ajpeacock0** [comment]
> # API Stewardship Rewview 18-Oct-21
> @ajpeacock0 & @jorgegarchirota all looks good. Minor stuff to fix...
> 
> * Parameter should have a description. (line 26)
> * The body parameter is not marked as required. (line 26)
> * Error response should contain a x-ms-error-code header. (line 41)

@markweitzel For _"The body parameter is not marked as required.  (line 26)"_ this was done since the two properties in `CommunicationRelayConfigurationRequest` are optional, so in the case the caller does not want to provide on, they wouldn't be forced to give an empty json object. 

Are you saying this optional request must be required, thus making the caller inclide a `{}` body?

**Comment by mikekistler** [comment]
Regarding the optional request body, if it is truly optional then this is fine. This is _often_ an oversight and that's why we flag it.  But I wonder -- in the even that the body properties are not provided, what is the behavior of the API?  There is no "default" value for these properties, so how will users know what to expect if they don't specify them?

**Comment by ajpeacock0** [comment]
>  There is no "default" value for these properties, so how will users know what to expect if they don't specify them?

That's a good point. Having no default was also intentional, since for `id` that doesn't make sense and for `routeType` we have the behavior or returning all if nothing is specified, but we don't indicate this. I'll add to the description for both to explain behavior
