### ISSUE TITLE
`Microsoft.DBforMySQL/flexibleServers` version `2021-05-01` documents property `fullyQualifiedDomainName` that does not exist service-side

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-rest-api-specs#16991]
Originally reported here:
https://github.com/Azure/bicep/issues/5328

**Comment by Suna-MS** [comment]
'fullyQualifiedDomainName' exists in server properties in file https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2021-05-01/mysql.json#L1743
and this property also returned in service side when Get server.

Since there is extension "x-ms-client-flatten": true set in server.properties, Should use mySqlServer.fullyQualifiedDomainName in bicep?

**Comment by alex-frankel** [comment]
Thanks - this looks like it is a bicep issue, not a swagger issue. Thanks for following up.
