### ISSUE TITLE
AzureRedHatOpenShift: Question regarding API Updates to `modelAsString:true` enums

### ISSUE THREAD

**Issue by bennerv** [Azure/azure-rest-api-specs#17694]
Service: ARO (Azure Red Hat OpenShift)
API Version:  `2021-09-01-preview`

We are currently adding VM Sizes to an enum defined in our API version. This API field can be seen [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/redhatopenshift.json#L839-L871).  

Since we're using `modelAsString: true`, when we want to add new enum types, should we submit a PR with the updated types, or is the list considered non-exhaustive so it doesn't need an update to the API definition in `azure-rest-api-specs` repo? 

Example below

### Current API
```json
   "VMSize": {
      "description": "VMSize represents a VM size.",
      "enum": [
        "Standard_D16as_v4"
      ],
      "type": "string",
      "x-ms-enum": {
        "name": "VMSize",
        "modelAsString": true
      }
    },
```

### New Updated enums
```json
   "VMSize": {
      "description": "VMSize represents a VM size.",
      "enum": [
        "Standard_D16as_v4",
        "Standard_D8s_v3" // New field now supported in our backend.  Once we update the backend do we need to ensure that this is added to the existing APIs? 
      ],
      "type": "string",
      "x-ms-enum": {
        "name": "VMSize",
        "modelAsString": true
      }
    },
```

**Comment by bennerv** [comment]
@qike-ms, @jwilder, @thomas1206, @seanmck  wondering if you guys have a minute to provide an answer.  
 
cc @weinong @bryanro92

**Comment by rahulm23** [comment]
Hello - can someone please approve this PR? It's time sensitive request and impacting customer facing features.

**Comment by JeffreyRichter** [comment]
Since you are adding the enum to the swagger (which is also how documentation is produced), the api-version should change to accurately reflect that the swagger has changed. Then, new SDKs should be generated so that the new enum value is exposed in the SDKs.

**Comment by bennerv** [comment]
@JeffreyRichter 

According to the [Breaking Change Doc](https://microsoft.sharepoint.com/:w:/t/azureresourcemanagerteam/EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw?e=xEcppo) Allowed values for an enum have changes is considered non-breaking.  Why would we need a new api-version to change if we're just adding a new value (since we're modeling the enum as a string)?

**Comment by JeffreyRichter** [comment]
The doc you linked to is not an official doc. Here is the official doc: https://aka.ms/AzBreakingChangesPolicy/ (MS internal)

This particular question is a hard one to answer and we've gone back and forth on how it would work multiple times. This is a problem with enum **values** since they are not a **type** and we frequently wish we didn't even have the concept of an enum at all. 

Technically speaking, the service's API is not changing and so the api-version shouldn't change -- I agree with this. But, we want a 1:1 relationship between a service's api-version and its contract (which is the swagger). So, if you modify the swagger (add a new enum value), then the swagger version _should_ change. And, we need to produce new SDKs to expose the new enum value and we like to tell customers which swagger api-version an SDK was built from. If you add a new enum value and do NOT change the api-version, then an SDK that targets the api-version may or may not expose the new enum value. This causes customer and Azure customer support services (CSS) confusion. All of this confusion is avoided by changing the api-version.

So, right now, the document I link to above does say, that a new enum value can be added to a swagger without changing the api-version and I'll honor that. But, we could reconsider this in the future. 

I'm open to thoughts/suggestions on this. Remember: The key is we're trying to optimize for the Azure customer experience and NOT for the Microsoft engineer experience. This does push me more towards the side of requiring the api-version change when adding a new enum value.

**Comment by JeffreyRichter** [comment]
I thought of some more things to say...

From an HTTP/REST API perspective, there is no such thing as an enum - they are just strings. To make things better for our documentation and SDK customers, the DevDiv autorest team created the concept of an enum in swagger so that docs/SDK customers were given string value suggestions. This was nice but it didn't consider the versioning implications of this: what happens when new values are introduced or when old values go away? From an HTTP/REST perspective the string hasn't changed; but from a documentation/SDK perspective, things have changed. If autorest never introduced the concept of an enum, then versioning is easy (and you wouldn't even be asking this question).

A lot of Azure customers do use our SDKs and certainly, they use our documentation. So now, the question is whether introducing this concept of enums is an overall net win or net loss because there are pros & cons to either choice? In general, we think enums are a net win but it does introduce new versioning issues.

**Comment by bennerv** [comment]
@JeffreyRichter 
Really appreciate the response.

It's definitely two-sided.  We (Azure resource provider teams) want to deliver features and asks from customers as quickly as possible and a simple ask which results in a full API release with review, automation, generation, az-cli updates, etc. has a lot of overhead (not just from our team), preventing the customer from getting the features they need as quickly as possible.  Definite contention even just trying to optimize the Azure customer's experience.
