### ISSUE TITLE
[Cognitive Services - Text Analytics] REST API Review for Text Analytics - Healthcare Task

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#17717]
•	Service name – Text Analytics Language API
•	Key contact for the review – :Thaminda.Edirisooriya@microsoft.com
•	Whether this is a new or existing API - Existing
•	Whether or not your service already been deployed - Yes
•	A brief description of the material to be reviewed/changed – Adding an optional task parameter that results in an additional string coming back in the API response

## Document & References
[Design Doc](https://microsoft-my.sharepoint.com/:w:/p/thediris/EdhfJXo2mctCtWJxPQK-6i0BgG7T5lDlyDzKv7FmJZYpKg?e=HGb6bS)

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 17-Feb-22


### Discussion / Notes

* There are a number of areas in the open api document that are missing descriptions and/or title. These should be added because they are automatically included in the [generated developer docs](https://review.docs.microsoft.com/en-us/rest/api/documentation-preview/analyze-text/analyze-text?view=azure-rest-preview&branch=result_174ff17c-0b24-454c-8684-bf4f009af28a).

### Actions
* Please refer to the [Azure Style Guidelines](https://aka.ms/azapi/specs). There you find instructions on using the spectal linter--this can be helpful in correcting some of the cleanliness issues with the swagger. 

## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1644360668945?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1644360668945&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1644360668945)
[Meeting Minutes]()
[Text Analytics in OpenAPI Editor](https://swagger.microsoft.com/designer/apis/2hbwxg)
### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
