### ISSUE TITLE
[Purview - DataPolicy] REST API Review

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#17747]
Service name - Purview Data Policies
Key contact for the review - nayenama@microsoft.com, ksvijayv@microsoft.com, raanne@microsoft.com, prmujumd@microsoft.com
Whether this is a new or existing API : New API
Whether or not your service already been deployed: Yes , deployed
A brief description of the material to be reviewed/changed - Data plane API to allow customers to create data polices

**Comment by czubair** [comment]
Review scheduled for 3/2 at 9am PST

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 2-March-22

The context of the service, as well as the 

### Discussion / Notes
* Because the `update` is a whole object, consider changing `CreateOrUpdate` to `CreateOrReplace` as `Replace` is more clear and accurate to what the operation does. 
* We should talk about cnf and dnf names again. We really dislike those and would prefer oneOf, allOf, etc., names that make sense to regular humans, for example, `allOf`, `oneOf`. For example, the following `cnfCondition` could be `allOf`
```json
    "decisionRules": [
      {
        "effect": "Permit",
        "cnfCondition": [
          [
            {
              "attributeName": "resource.azure.path",
              "attributeValueIncludedIn": [
                "/subscriptions/e6e0a165-6a3b-4d0d-a611-d153bf286620/resourceGroups/some-rg/**"
              ]
            }
          ],
          [
            {
              "attributeName": "principal.microsoft.id",
              "attributeValueIncludedIn": [
                "1a5c6fb7-d72e-486c-8262-c3cd85cfde07"
              ]
            }
          ],
          [
            {
              "attributeName": "derived.purview.role",
              "attributeValueIncludes": "purviewdatarole_builtin_read"
            }
          ]
        ]
      }
    ],
```

* Consider flattening the model structure by removing `properties`. Unless this structure is absolutely necessary. 
> @kshitizvijay -- Follow up and comment here on the decision

* Remove the `count` on the `dataPolicies`. This is very expensive if done across all pages. And since the current usage is just the size of the array that is returned, it's not very helpful. 

* The `PUT` for `/dataPolicies/{policyName}/scopes` operation should have an id at the end. Consider:
> `/dataPolicies/{policyName}/scopes/{scopeId}`
> If there are different body types, then introduce an extensible enum with `kind` and add this as a field in the body. 

* Note: `error` structure matches what is used across Purview and does not match the current REST API Guidelines.

## Actions
* Purview team will update the API Document via the PR and request a review. 


## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1644469477078?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1644469477078&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1644469477078)
[Meeting Recording]()

### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by kshitizvijay** [comment]
The Purview team has agreed to all changes 

> ## API Stewardship Board Review Meeting 2-March-22
> The context of the service, as well as the
> 
> ### Discussion / Notes
> * Because the `update` is a whole object, consider changing `CreateOrUpdate` to `CreateOrReplace` as `Replace` is more clear and accurate to what the operation does.
> * We should talk about cnf and dnf names again. We really dislike those and would prefer oneOf, allOf, etc., names that make sense to regular humans, for example, `allOf`, `oneOf`. For example, the following `cnfCondition` could be `allOf`
> 
> ```json
>     "decisionRules": [
>       {
>         "effect": "Permit",
>         "cnfCondition": [
>           [
>             {
>               "attributeName": "resource.azure.path",
>               "attributeValueIncludedIn": [
>                 "/subscriptions/e6e0a165-6a3b-4d0d-a611-d153bf286620/resourceGroups/some-rg/**"
>               ]
>             }
>           ],
>           [
>             {
>               "attributeName": "principal.microsoft.id",
>               "attributeValueIncludedIn": [
>                 "1a5c6fb7-d72e-486c-8262-c3cd85cfde07"
>               ]
>             }
>           ],
>           [
>             {
>               "attributeName": "derived.purview.role",
>               "attributeValueIncludes": "purviewdatarole_builtin_read"
>             }
>           ]
>         ]
>       }
>     ],
> ```
> 
> * Consider flattening the model structure by removing `properties`. Unless this structure is absolutely necessary.
> 
> > @kshitizvijay -- Follow up and comment here on the decision
> 
> * Remove the `count` on the `dataPolicies`. This is very expensive if done across all pages. And since the current usage is just the size of the array that is returned, it's not very helpful.
> * The `PUT` for `/dataPolicies/{policyName}/scopes` operation should have an id at the end. Consider:
> 
> > `/dataPolicies/{policyName}/scopes/{scopeId}`
> > If there are different body types, then introduce an extensible enum with `kind` and add this as a field in the body.
> 
> * Note: `error` structure matches what is used across Purview and does not match the current REST API Guidelines.
> 
> ## Actions
> * Purview team will update the API Document via the PR and request a review.
> 
> ## References
> [Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1644469477078?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1644469477078&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1644469477078) Meeting Recording [Transcript](https://github.com/Azure/azure-rest-api-specs/files/8171824/Transcript_057d9d8a-9c9e-4454-8052-f13cab24c4f2.docx)
> 
> ### Helpful Documentation
> [Azure API REST Documentation](https://aka.ms/azapi/specs)

The Azure Purview team has agreed upon all changes except changes to cnfCondition/dnfCondition .
We already have a lot of our RPs using this nomenclature. We would like to keep it as it is.

**Comment by czubair** [comment]
@kshitizvijay please ping @mikekistler for a re-review/to coordinate final approval.

**Comment by kshitizvijay** [comment]
renaming of cnf and dnf is not being agreed by the Purview team.
The rest of the requested changes have been accepted.

**Comment by kshitizvijay** [comment]
Hi @markweitzel , I have updated the PR
https://github.com/Azure/azure-rest-api-specs/pull/19076

Can we continue with the review?

**Comment by tg-msft** [comment]
> renaming of cnf and dnf is not being agreed by the Purview team.

@kshitizvijay - Can you tell me more about why these names are the right names from your team's perspective?  From what I remember in the review meeting, these aren't terms or concepts from the security industry/domain but rather formal logic's [dnf](https://en.wikipedia.org/wiki/Disjunctive_normal_form)/[cnf](https://en.wikipedia.org/wiki/Conjunctive_normal_form).  Are there other products in the security space that use these terms?  Do you have any data that your target customers will be familiar with dnf/cnf for defining rules?  Can we have someone on your PM team run these names by five potential customers to get their reactions?  I worry that arrays called dnf/cnf don't meet the usability bar we have for the Azure SDK developer experience and your client libraries will diverge from your REST API.
