### ISSUE TITLE
checkZonePeers API is not functional

### ISSUE THREAD

**Issue by r0kas** [Azure/azure-rest-api-specs#17941]
"/subscriptions/{subscriptionId}/providers/Microsoft.Resources/checkZonePeers/" API is not functional through REST API.

Nor SDKs nor Azure Docs API helper works with neither API version.

`{"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Resources' for api version '2021-01-01'."}}`

@tjegbejimba and @msyyc added a [commit](https://github.com/Azure/azure-rest-api-specs/commit/5d117a8c7686fe2b2940114f6866a3958ccca6e0) to support the endpoint on REST API specs, not sure where this part is implemented. 
Would be willing to contribute if needed.

**Comment by wsmelton** [comment]
Related MicrosoftDocs/azure-docs#85742

**Comment by Br0k3nByD3s1gn** [comment]
In today's 'Datacenter Cooling Event - Southeast Asia' Disaster Email (tracking ID: RV44-JT0) there was a part where we could check if our resources are in the impacted zone AZ3 or not. It was linking to this in MS learn: [here](https://learn.microsoft.com/rest/api/resources/subscriptions/check-zone-peers?tabs=HTTP).

Of course it does not work since in the Resource Provider: Microsoft.Resources the Resource Type: checkZonePeers is missing.

Googling the Errormessage brought me to this open Git issue so this feature we shall use seems to be broken for almost a year. 

Please fix.

**Comment by Br0k3nByD3s1gn** [comment]
Very sorry, turns out the Resource Type needs to be registered too, not just the Resource Provider:
This issue should be marked as closed as it seems to be, actually, working correctly right now.
If anyone else has the same problem, to register the Resource Type:
`Register-AzProviderFeature -FeatureName AvailabilityZonePeering -ProviderNamespace Microsoft.Resources`
Check status of the Resource Type:
`get-AzProviderFeature -FeatureName AvailabilityZonePeering -ProviderNamespace Microsoft.Resources`

**Comment by ericsuhong** [comment]
Can we add this to a documentation or make error return more helpful message? I was faced with the same error from ARM API and was confused.
