### ISSUE TITLE
[Communication Services - JobRouter] REST API Review

### ISSUE THREAD

**Issue by cparisineti** [Azure/azure-rest-api-specs#18013]
- Service name: ACS Job Router
- Key contact for the review: Bo Gao (bga@microsoft.com)
- Whether this is a new or existing API - New API
- Whether or not your service already been deployed - yes
- A brief description of the material to be reviewed/changed - APIs (swagger model) has been reviewed with Jeffrey Richter. This PR includes  swagger definition and examples for JobRouter.

**Comment by cparisineti** [comment]
Pull request: https://github.com/Azure/azure-rest-api-specs/pull/17872/

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting  8-March-22


### Discussion / Notes
* Use `PATCH` or `PUT` for creation. The `id` will be classified as OII data and not classified as customer content. Even if it was classified as customer content, this is still allowed.
* `queueSelectors` and `workerSelectors`
  * Order in the array does not matter
  * These are only primitive values. They are `and'ed` together 

* For `GET` `routing/jobs` 
  * IF there are more sophisticated filter conditions that are necessary, consider adding a more robust filter language instead of `and'ing` the two properties. 

* For `TTL`: We are encouraging customers to move away from ISO8601 
  * Consider not using ISO8601 durations in the PXX format because there's not great support or understanding (on things like selector's ttl). Instead pick a granularity (seconds, minutes, hours, ?) and allow people to define the number of those units for ttl.
  * This should apply to all your durations

### Actions
* Sync with @JeffreyRichter off-line on privacy concerns
* Mark - provide example of default response

## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1646071045705?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1646071045705&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1646071045705)
[Meeting Recording]()

### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by mikekistler** [comment]
Notes from REST API Review 5/30/23

- What are the competitors to this service?
- maxpagesize should be all lowercase
- limit consumes to "application/json"
- "unavailableForMatching" seems like it is a double-negative, maybe because the default is false?
   - maybe change this from boolean to an enum? That will fix the double-negative naming and allow more options to be expressed.
   - maybe a polymorphic type: JobMatchingMode
- Could "waitForActivation" be a query parameter rather than in the request body?
- Why "modelAsString: false"? We recommend "modelAsString: true"
- JobStatus values should use our LRO terminal state values, even if this isn't a "true" LRO
- Could "reofferTimeUTC" be a query parameter?
- Could you remove "UTC" from the names of date-time values?

This looks good for preview after clean up of the minor issues.
