### ISSUE TITLE
[Purview - Insights ] REST API Review

### ISSUE THREAD

**Issue by balassit** [Azure/azure-rest-api-specs#18520]
Service name: Insights
Key contact for the review: balassit
Whether this is a new or existing API: new
Whether or not your service already been deployed: already deployed

New data plane API to review - #18372
[Scope and UX feature view](https://microsoft.sharepoint.com/:p:/t/ProjectBabylon/EeFhh4JB8chEjGWMjjGUK64BLQ59ugXnY2c-F94LyBPy2Q?e=Yhe8do)
[Design](https://microsoft.sharepoint.com/:u:/t/ProjectBabylon/EdJe5vuhuSlMps1YOuY7FYABZMqxuC1YmkJzHZ4ICgD77g?e=pPgh1I)

**Comment by markweitzel** [comment]
## API Stewardship Review 13-APR-22

### Discussion / Notes
* Make all the collections pageable using next link to avoid breaking changes in the future.
* Consider removing the polymorphism and using a single method for each type.
  * /assets/snapshots-<kind>
  * If you do this, you can remove the `kind` field in the body
  * This feels like an RPC like API 
  * Check the data structure of `Error` that is in the Guidelines. Change `errorCode` to `code`. Try to remove what's not used/needed
* Verify that there is an `api-version` parameter in the API definitions
* The use of `orderby` locks you into a  SQL store b/c it's very difficult/hard to compute in other kinds of data stores
   * Consider removing `count`

**Comment by balassit** [comment]
- renaming type to tagType to keep consistency with other APIs

**Comment by weidongxu-microsoft** [comment]
Pending task, explanation on following feedback
- Consider removing the polymorphism and using a single method for each type.
- The use of `orderby` locks you into a SQL store b/c it's very difficult/hard to compute in other kinds of data stores

**Comment by balassit** [comment]
For both of these, we are ok with it as is

**Comment by markweitzel** [comment]
@balassit  & @nayenama,
WRT the use of polymorphism: The board revisited this discussion in a recent leadership team meeting and we all agreed and strongly recommend that you expand the API surface and avoid using polymorphism. There are many reasons for this, for example:
* Developers will be forced to write numerous casting and switch statements in order to use your API. This will make things challenging to maintain, and difficult to evolve over time. 
* There will be no good experience in tooling, for example, intellisense will not work.
* Developer documentation will be difficult and confusing.

One thing we would strongly encourage you to do is generate out a simple client in a typed language and write code against your API. You will quickly experience many of the same pain points that developers will face when using your API. 

As a Stewardship team, we are STRONGLY RECOMMENDING not using polymorphism in this API.

**Comment by balassit** [comment]
Yes, we do use our own typed client for our own purposes of functional test integration. There are several ways to use polymorphism cleanly; switches and cast can be abstracted into adapters. We acknowledge the board’s consideration, however, our plan is to release the API with the existing structure.

All of these discussions took place within our team prior to SDK review and we did weigh out these trade offs beforehand (to be clear that thought and approval from our team took place, not just my perspective as the driver of our SDK work item)

**Comment by mikekistler** [comment]
Linked PR has been closed without merge, so closing out this issue.
