### ISSUE TITLE
[DigitalTwins] REST API Review

### ISSUE THREAD

**Issue by sjiherzig** [Azure/azure-rest-api-specs#18792]
**Service name:** Azure Digital Twins

**Key contact for the review:** Sebastian Herzig-Patel (@sjiherzig)

**Whether this is a new or existing API:** new API version, but no changes to existing APIs

**Whether or not your service already been deployed:** no

**A brief description of the material to be reviewed/changed:**
This API version derives from 2021-06-30-preview and the swagger has no changes other than omitting the enumeration literals for the api-version parameter. There are no behavioral changes w.r.t. 2021-06-30-preview. This API version is mainly introduced in order to provider a stable API version for the GA release of the ADT Data History feature and the accompanying support for setting the "sourceTime" property.

**Comment by czubair** [comment]
Request for an async review

Note on Swagger PR: there is a model validation failure that seems to stem from the fact that we use an “object” type as the return type. We have done this in the past, since the response depends on a customer-defined model and / or the query being posed. Please advise what the best strategy forward here is.

**Comment by czubair** [comment]
@weidongxu-microsoft  could you make an initial pass on this PR.

**Comment by weidongxu-microsoft** [comment]
@czubair 
I've done a quick check. There is no API change since last stable version of 2020-10-31.

@sjiherzig
Would you let us know why this new api-version got no change from 2020-10-31?
2020-10-31 https://github.com/Azure/azure-rest-api-specs/blob/main/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2020-10-31/digitaltwins.json
2022-05-31 https://github.com/Azure/azure-rest-api-specs/blob/a6f77c4c785e04acd35b8737e56e3005eb0a2dca/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2022-05-31/digitaltwins.json
(one can do diff, or just count the line number of 2 jsons)

**Comment by sjiherzig** [comment]
Hi Weidong,

The API changes are primarily behavioral in nature and the API review guide requested us to introduce a new API version for these.

Specifically, responses (which largely depend on customer-defined schemas) can now include extra metadata. For instance:

2020-10-31:
```
GET /digitaltwin/myTwin
{
    "id": "1234",
    "temperature": 10.0,
    "$metadata": {
        "$model": "dtmi::model1",
        "temperature": {
            "lastUpdateTime": "2020-10-31T19:00:01.001348Z"
        }
    }
}
```

2022-05-31:
```
GET /digitaltwin/myTwin
{
    "id": "1234",
    "temperature": 10.0,
    "$metadata": {
        "$model": "dtmi::model1",
        "temperature": {
            "lastUpdateTime": "2020-10-31T19:00:01.001348Z",
            **"sourceTime": "2020-10-31T19:00:00.984738Z"**
        }
    }
}
```

The new API version intrdocues the additional metadata property "sourceTime" (highlighted above), which can also be set in a PUT request. This was previously not possible and the only metadata that could be changed in the past was the $model property.

There's a similar change to returning a "lastUpdatedTime" in the $metadata block, which I need to add to the examples.

**Comment by weidongxu-microsoft** [comment]
@sjiherzig

Got it. The request and response of digitalTwin is both type=object. Hence I didn't see any change in schema and model.

**Comment by sjiherzig** [comment]
All comments should now be addressed - I've also incorporated changes requested from a previous review of API version 2022-02-28-preview (which has not yet been released). These are minor and consisted of:
* Ensuring required = true for "value" field in paged responses from _List APIs
* Body of DigitalTwinModels_Add and EventRoutes_Add APIs are marked required = true

Per decision in https://github.com/Azure/azure-rest-api-specs-pr/issues/5257, I've also removed the 202 responses, since these are never returned by the service.

**Comment by czubair** [comment]
Thanks, @sjiherzig . @weidongxu-microsoft I requested a re-review from you on the PR.

**Comment by weidongxu-microsoft** [comment]
Sebastian confirmed that "x-ms-error-code" is in backlog and will be supported in next GA release.

Signed off from me. It is OK to merge.
