### ISSUE TITLE
[Communication - Phone Number Service] REST API Review

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#18871]
Service name:
ACS - Phone Number Service

Key contact for the review:
adrian.tang@microsoft.com

Whether this is a new or existing API:
Existing API

PR
https://github.com/Azure/azure-rest-api-specs/pull/18869

Previous REST.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/PhoneNumbers/stable/2021-03-07/phonenumbers.json

[Hero scenarios](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/31514/Hero-Scenarios)

There are four new proposed APIs:
API that returns the list of eligible countries for the Azure resource.
API that returns the list of offerings given a country.
API that returns the list of available cities with phone numbers available, given a country.
API that returns the list of available area codes, given a city.

**Comment by markweitzel** [comment]
## API Stewardship Board Review 10-May-22

* `top` has been implemented as though it were `maxpagesize`. Because some of these APIs have GA'd with an implementation of `top` this way, then this should be consistent within the service.
  *   
[API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md)

**Comment by mikekistler** [comment]
@whisper6284 Following up on the discussion of "top" in the API review meeting yesterday: we did a little more investigation and it appears that there is just one operation, `ListPhoneNumbers` that has been GA'ed with an incorrect "top" parameter, and the updated API we reviewed yesterday adds 4 more instances where "top" is defined incorrectly.

If this is correct, we'd like to modify/update the advice on how this should be handled.

We propose the following:

- The one GA'ed operation with "top" will be left as is, though the current description should be improved to make clear that this is the number of entries _per page_ (that's missing today).

- The four new operations should define "maxpagesize" instead of "top" -- per our Guidelines.  I think you should not define a default for maxpagesize either, so that the service can decide on page size dynamically.

- Going forward, any list operations added in the future will use "maxpagesize" rather than "top".

This will make "one odd operation" which is not great, this is preferable to "one odd service".

You could add a "maxpagesize" query parameter to `ListPhoneNumbers`, which would provide some consistency with the other list operations.  This will make it slightly "more odd" in that it has two parameters that do essentially the same thing, but it was already odd, so I think the net is probably positive. If you do this, then the service should fail if both query params are specified. The docs can say that top is obsolete and should be avoided; use maxpagesize instead.

I hope this is clear but feel free to respond here or through email if you have any questions.

**Comment by whisper6284** [comment]
Thank you @mikekistler . I will investigate the back-end service to ensure that not having a default size for maxpage size and having page size dynamic is feasible.

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
