### ISSUE TITLE
[BotService] unexpected channelName warning

### ISSUE THREAD

**Issue by kuojianlu** [Azure/azure-rest-api-specs#18951]
bicep version: v0.6.1.

```bicep
// Connect the bot service to Outlook
resource botServiceOutlookChannel 'Microsoft.BotService/botServices/channels@2021-05-01-preview' = {
  parent: botService
  location: 'global'
  name: 'OutlookChannel'
  properties: {
    channelName: 'OutlookChannel'
  }
}
```
![image](https://user-images.githubusercontent.com/37978464/167242148-abc9dfa9-24c9-4e87-b36a-584d999bf4f5.png)

**Comment by navba-MSFT** [comment]
@kuojianlu Apologies for the late reply. Thanks for getting back and sharing this feedback. Could you please elaborate this ask ? May I know your use case ? What are your trying to accomplish ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kuojianlu Thanks for getting back. I am looking into this ask. I will get back if I need more details from you.

**Comment by navba-MSFT** [comment]
@kuojianlu I could see in the restapi specs that the enum value for the Outlook has been added correctly for 2021-05-01-preview. see below:

>"enum": [
        "AlexaChannel",
        "FacebookChannel",
        "EmailChannel",
        "KikChannel",
        "TelegramChannel",
        "SlackChannel",
        "MsTeamsChannel",
        "SkypeChannel",
        "WebChatChannel",
        "DirectLineChannel",
        "SmsChannel",
        "LineChannel",
        "DirectLineSpeechChannel",
        "**OutlookChannel**"
      ]

Refer [this](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/preview/2021-05-01-preview/botservice.json). 

**_Action Plan:_**
Could you please update your template to use the below and check if that helps ? Awaiting your reply. 

> channelName: '**outlook**'

**Comment by kuojianlu** [comment]
@navba-MSFT Yes, I know this change. The code snippet above is the latest. 

Please note that there are two `OutlookChannel` in the code snippet. The first one `name: 'OutlookChannel'` works perfectly. But the second one `channelName: 'OutlookChannel'` causes a warning.
```bicep
// Connect the bot service to Outlook
resource botServiceOutlookChannel 'Microsoft.BotService/botServices/channels@2021-05-01-preview' = {
  parent: botService
  location: 'global'
  name: 'OutlookChannel'
  properties: {
    channelName: 'OutlookChannel'
  }
}
```

**Comment by navba-MSFT** [comment]
@kuojianlu Thanks for getting back. I wanted to check the outcome of my action plan. Could you please check and let me know if `channelName: 'outlook'` generated the same warning ? Awaiting your reply.

In the meantime, I am checking on your code snippet too. I will keep you posted.

**Comment by kuojianlu** [comment]
@navba-MSFT Yes.

**Comment by navba-MSFT** [comment]
@kuojianlu The spec change linked to did add “OutlookChannel” to the[ channelNameParameter definition ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/preview/2021-05-01-preview/botservice.json#L3166)used by the [channelName path parameter](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/preview/2021-05-01-preview/botservice.json#L332-L334), but the channelName property in the request body is defined separately. The property is the discriminator for the [Channel discriminated union type](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/preview/2021-05-01-preview/botservice.json#L1845), for which no OutlookChannel child is defined. A separate object with an x-ms-discriminator-value of “OutlookChannel” (cf the [AlexaChannel definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/preview/2021-05-01-preview/botservice.json#L1871-L1886) for an example) will need to be added to the Swagger document in order to clear up the reported BCP088 warning which you have reported. I have reached out to the concerned team to get the service model updated.

**Comment by kuojianlu** [comment]
@navba-MSFT Thanks a lot. Good to know that you have reached out to the concerned team and the service model will be updated!

**Comment by navba-MSFT** [comment]
@kuojianlu If you need any further assistance on this feel free to let me know.

**Comment by navba-MSFT** [comment]
@kuojianlu Since we have got a confirmation from the Product Owners that the issue will be fixed after a month or two, we will proceed with closure of this GitHub thread. We will update this thread once the fix is released. If you have any queries on this, please feel free to reopen this GitHub thread. We would be happy to help.
