### ISSUE TITLE
Bad request in resource filtering

### ISSUE THREAD

**Issue by piotrszajer** [Azure/azure-rest-api-specs#21324]
- azure-mgmt-resource 
- 21.2.1
- Ubuntu 22:
- Python 3.9: 

**Describe the bug**
Filtering is not working when combined

**To Reproduce**
This works:
```
list( 
self.resource_client.resources.list(filter="tagName eq 'myTag' and tagValue eq 'myValue' ")
)
```
This also works:
```
list( 
self.resource_client.resources.list(filter="resourceType eq 'Microsoft.Compute/virtualMachines'  ")
)
```
But this does not work - Bad Request
```
list( 
self.resource_client.resources.list(filter="tagName eq 'myTag' and tagValue eq 'myValue' and resourceType eq 'Microsoft.Compute/virtualMachines' ")
)
```
**Expected behavior**
Properly filtered items will be returned

**Comment by navba-MSFT** [comment]
@piotrszajer Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

Looking at the[ Resources - List REST API ](https://learn.microsoft.com/en-us/rest/api/resources/resources/list) seems like this is an expected behavior.

The description of the` $filter `query string mentions the below:

> Note that some properties can be combined when filtering resources, which include the following: substringof() and/or resourceType, plan and plan/publisher and plan/name, and identity and identity/principalId.

So `resourceType` filtering property can only be combined with `substringof()` property.

**Example:** (resourceType eq 'Microsoft.Compute/virtualMachines' and substringof('azure', name))

More Info about `substringof` substringof(value, property) can be used to filter for substrings of the following currently-supported properties: name and resourceGroup

**Comment by navba-MSFT** [comment]
@piotrszajer I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@piotrszajer The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
