### ISSUE TITLE
azure_api should support flexible server postgresql createMode Replica since it's now in public preview

### ISSUE THREAD

**Issue by SebTardif** [Azure/azure-rest-api-specs#21453]
The announcement: https://azure.microsoft.com/en-us/updates/public-preview-read-replicas-for-azure-database-for-postgresql-flexible-server/

The api to update: See https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L1479

**Comment by navba-MSFT** [comment]
@SebTardif Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this and we will get back to you with an update.

**Comment by navba-MSFT** [comment]
@SebTardif You can refer this latest preview swagger changes here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-03-08-preview/FlexibleServers.json

Hope this helps.

**Comment by navba-MSFT** [comment]
@SebTardif Looking at your other issue thread https://github.com/Azure/azure-rest-api-specs/issues/21438 seems like your issue is addressed. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
