### ISSUE TITLE
Azure Search Service API Spec Updates

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-rest-api-specs#22]
It looks like only the Search Management API (https://msdn.microsoft.com/en-us/library/azure/dn832684.aspx) has a spec to date. It would be great to get an updated spec to include the entirety of the Search Search API (https://msdn.microsoft.com/en-us/library/azure/dn798935.aspx). This would further the efforts to expand the arm support being built out for the Go SDK as described [here](https://github.com/Azure/azure-sdk-for-go/issues/114).

**Comment by brjohnstmsft** [comment]
Hi @anweiss 

I'm on the Azure Search team and I work on the REST API and Azure Search SDK.

I'd like to clarify a few things about the state of the Azure Search SDKs as they relate to Swagger and AutoRest.
- There is no shipping Azure Search Management SDK at this time. The Swagger spec under `arm-search` is used to generate a partial management client library that is used only for testing the main Search SDK. Eventually we will ship a Management SDK, but there has been very little customer demand for it to date, so it is not a priority for us right now.
- The main Search SDK has no dependency on ARM because it is a data-plane SDK, not a management SDK. A customer would use the Search SDK to call directly to their Search service, not to ARM. If you opened this issue to track work strictly related to ARM, we should close it because it doesn't apply to the Search SDK that we're actually shipping today.
- For various reasons, it is not possible (and will likely never be possible) to use AutoRest to generate all of the Search SDK code. There are a lot of details here, but the general problem is that Search returns a lot of structured data with schemas that aren't known until run-time. For strongly-typed languages that support generics, we'd like to provide our customers with ways to use their own model types. AutoRest was not designed to generate code that can do this. This means...
- ...that in order for us to ship a Go SDK for Azure Search, it requires some effort on our part (it's not just a matter of running AutoRest on a Swagger spec and presto, there's a new SDK). Right now we're in the process of migrating our .NET SDK to AutoRest. After that, we'll evaluate which languages/platforms to support next. If there is real customer demand for Go, that would be great to hear about and I'd encourage you to contact me offline.

**Comment by anweiss** [comment]
Thanks for the insight @brjohnstmsft! I can reach out to you offline for more details.
