### ISSUE TITLE
SQL BlobAuditing Log Analytics and Eventhub Support

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#22063]
In the portal, we can specify Log Analytics and EventHub as places to store SQL server audit logs but that functionality doesn't appear to be in the API.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/6515518/210662195-e5286a4f-559d-4fa2-949b-243cce08b95c.png">

I've looked through all of the existing API properties for Audit Logs and there doesn't appear to be support anywhere for it.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2022-05-01-preview/BlobAuditing.json#L976

**Comment by navba-MSFT** [comment]
@mbfrahry  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mbfrahry 

[Create or Update Server Auditing Policy](https://learn.microsoft.com/en-us/rest/api/sql/2017-03-01-preview/server-auditing-settings/create-or-update)

Create or update a server's blob auditing policy PUT REST API operation is [**here**](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2022-05-01-preview/BlobAuditing.json#L102).

Could you please let me know if this helps ?

**Comment by navba-MSFT** [comment]
@mbfrahry I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mbfrahry** [comment]
Hi @navba-MSFT, unfortunately that link you shared just supports storage for auditing. We're looking to be able to support eventhub and log analytics as well.

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for your reply. I am sharing the below details about the underlying REST API call that is invoked while enabling the SQL auditing for Log Analytics and Event Hub:

**Log Analytics**

```
Request URL: 'https://management.azure.com/subscriptions/XXXXXXXXXX/resourceGroups/Databases-Resources/providers/Microsoft.
Sql/servers/MYSQLDB/databases/master/providers/Microsoft.Insights/diagnosticSettings/SQLSecurityAuditEvents_3d229c42-c7e7-4c97-9a99-ec0d0d8b86c1?api-version=2021-05-01-preview'
Request method: 'PUT'
Request headers:
  'Content-Type': 'application/json'
  'Content-Length': '327'
  'Accept': 'application/json'
  'Authorization': '*****'

Request body:
 {"properties": {"metrics": [], "logs": [{"category": "SQLSecurityAuditEvents", "enabled": true, "retentionPolicy": {"enabled": false, "days": 0}}], 
"workspaceId": "/subscriptions/XXXXXXXXXXXXXX/resourceGroups/defaultresourcegroup-wus2/providers/Microsoft.OperationalInsights/workspaces/MyLogAnalytucs"}}
```

**Event Hub:**

```
Request URL: 'https://management.azure.com/subscriptions/XXXXXXXXXXXXXXXX/resourceGroups/Databases-Resources/providers/Microsoft.
Sql/servers/MYSQlServerName/databases/master/providers/Microsoft.Insights/diagnosticSettings/SQLSecurityAuditEvents_c670e65f-f8d5-494f-b6a3-c8669e45bb81?api-version=2021-05-01-preview'
Request method: 'PUT'
Request headers:
  'Content-Type': 'application/json'
   'Content-Length': '348'
   'Accept': 'application/json'
   'Authorization': '*****'

Request body:
     {"properties": {"eventHubAuthorizationRuleId": 
"microsoft.eventhub/namespaces/authorizationrules", "eventHubName": "MyEHName", 
"logs": [{"category": "SQLSecurityAuditEvents", "enabled": true, "retentionPolicy": {"enabled": false, "days": 0}}]}}

```

**Comment by mbfrahry** [comment]
Thanks for that info @navba-MSFT, unfortunately that doesn't seem to be usable outside of directly calling the api because it's not in the api specs. Can that be made available [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2021-05-01-preview/BlobAuditing.json)?

**Comment by navba-MSFT** [comment]
@mbfrahry Enabling audit to Log analytics and event hubs is indeed supported through REST API.
Refer to https://learn.microsoft.com/en-us/rest/api/sql/2021-08-01-preview/server-blob-auditing-policies/create-or-update?tabs=HTTP#request-body

You need to pass in the request body: `'isAzureMonitorTargetEnabled'` as **True** for logs to go to Azure monitor targets i.e. Log analytics / Event hubs.

In addition to using above Rest API for audit configuration, you need to configure diagnostic settings using the Diagnostic settings API (which I have already mentioned [above](https://github.com/Azure/azure-rest-api-specs/issues/22063#issuecomment-1379872073)) for auditing to work.

An excerpt from the public documentation: 

<html>
<body>


properties.isAzureMonitorTargetEnabled |   | boolean | Specifies whether audit events are sent to Azure Monitor. In order to send the events to Azure Monitor, specify 'State' as 'Enabled' and 'IsAzureMonitorTargetEnabled' as true.When using REST API to configure auditing, Diagnostic Settings with 'SQLSecurityAuditEvents' diagnostic logs category on the database should be also created. Note that for server level audit you should use the 'master' database as {databaseName}.Diagnostic Settings URI format: PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/providers/microsoft.insights/diagnosticSettings/{settingsName}?api-version=2017-05-01-previewFor more information, see Diagnostic Settings REST API or Diagnostic Settings PowerShell
-- | -- | -- | --



</body>
</html>

**Comment by mbfrahry** [comment]
Ahhh, there it is. Thank you so much!

**Comment by mbfrahry** [comment]
So I've done as you've suggested where I have `isAzureMonitorTargetEnabled` set to true and I've got diagnostic monitoring for both eventhub and log analytics pointing at the sql server and I can see them in the portal under Monitor | Diagnostic Settings. 

The issue is that they are not linked under the Azure Sql Auditing section of the resource. Now, it's automatically connected to a default log analytics workspace but not the one that I've created specifically to hold the audit information. And I don't see how to connect the eventhub monitor diagnostic setting 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/6515518/213000757-f6be9763-9663-4a43-8aa4-a8735f3130f6.png">

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for your reply. Could you please confirm if you used the right Request Body while invoking the REST API ? 

You can see my [above ](https://github.com/Azure/azure-rest-api-specs/issues/22063#issuecomment-1379872073)comment which has the right request body. Please check if that helps.

**Comment by mbfrahry** [comment]
I've confirmed it on my end that I've sent what you have suggested. Can you confirm it on yours to see if sending that that request checks the boxes for Azure SQL Auditing?

**Comment by levgoronshteyn** [comment]
@navba-MSFT could you please provide feedback on @mbfrahry  comment above?

**Comment by navba-MSFT** [comment]
@mbfrahry I was discussing this issue internally with our Azure SQL product Group team. 

I did some more research on this and then ran the below AzureCLI command to enable the auditing and captured the **--debug** traces to identify the underlying REST API. So we could see that there are 2 PUT operations invoked in the background. 

**CLI command I executed:**
> **az sql server audit-policy update -g Databases-Resources -n MySQLName --state Enabled --lats Enabled --lawri /subscriptions/XXXXX/resourcegroups/Databases-Resources/providers/Microsoft.OperationalInsights/workspaces/MyLogAnalytics --debug**

**First PUT Request is to **[this REST API](https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP)****

Request URL: 'https://management.azure.com/subscriptions/XXXXX/resourceGroups/Databases-Resources/providers/Microsoft.Sql/servers/MySQLName /databases/master/providers/Microsoft.Insights/diagnosticSettings/SQLSecurityAuditEvents_97a188cb-80bc-46ec-8ae1-3643e6a7bc0a?api-version=2021-05-01-preview'

Request method: 'PUT'
Request headers:
'Content-Type': 'application/json'
'Content-Length': '299'
'Authorization': '*****'
**Request body:**
{"properties": {"logs": [{"category": "SQLSecurityAuditEvents", "enabled": true, "retentionPolicy": {"enabled": false, "days": 0}}], "workspaceId": 
"/subscriptions/XXXXXXX/resourcegroups/Databases-Resources/providers/Microsoft.OperationalInsights/workspaces/MyLogAnalytics"}}





**Second PUT Request to[ **this REST API**](https://learn.microsoft.com/en-us/rest/api/sql/2021-08-01-preview/server-blob-auditing-policies/create-or-update)**

Request URL: 'https://management.azure.com/subscriptions/XXXXX/resourceGroups/Databases-Resources/providers/Microsoft.Sql/servers/MySQLName/auditingSettings/default?api-version=2021-11-01-preview'
Request method: 'PUT'
Request headers:
'Content-Type': 'application/json'
'Content-Length': '365'
'Authorization': '*****'
**Request body:**
{"properties": {"isDevopsAuditEnabled": false, "retentionDays": 0, "auditActionsAndGroups": ["SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP", 
"FAILED_DATABASE_AUTHENTICATION_GROUP", "BATCH_COMPLETED_GROUP"], "isAzureMonitorTargetEnabled": true, "isManagedIdentityInUse": false, "state": "Enabled", "storageAccountSubscriptionId": 
"00000000-0000-0000-0000-000000000000"}}

With that My auditing settings was saved successfully in the portal:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/57353862/213640265-a5a6bfa4-055e-4f12-8f10-e92ac18372bb.png">

Please try the above action plan and if you still face the same issue and if this issue is very critical, Could you please open a support request so that Microsoft Support professional can work closely with you ?

**Comment by mbfrahry** [comment]
Thanks for that @navba-MSFT but that is for SQL Database Auditing. It does not work for SQL Server Auditing. I can manage it in the portal but I don't have a way to see that information from the API through Listing all the diagnostic settings attached to the sql server or Listing all the Auditing information from the sql server

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for your reply. The CLI command that I ran above is for Server auditing and not database level auditing. And the above mentioned REST APIs is what it was invoking underneath. 

As mentioned earlier, I have invoked the same 2 APIs and got it work at my end. See below the 200 status success code and the screenshot of the portal:

[ REST API 1 ](https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP)
<img width="671" alt="image" src="https://user-images.githubusercontent.com/57353862/213870260-08ad746b-6d1a-4f06-9b77-ec60f7f68c16.png">

[REST API 2](https://learn.microsoft.com/en-us/rest/api/sql/2021-08-01-preview/server-blob-auditing-policies/create-or-update)
<img width="615" alt="image" src="https://user-images.githubusercontent.com/57353862/213870396-3777018f-1c1b-4935-848c-cb38d9385b0d.png">


After invoking the 2 APIs the setting is saved successfully for my LogAnalytics workspace. See the below screenshot:

![image](https://user-images.githubusercontent.com/57353862/213870178-4e9a26fd-972a-40e5-b246-61b9defb39b4.png)

If you are still facing the issue, I would suggest you to open a support support ticket request so that Microsoft Support professional can work closely with you.

**Comment by mbfrahry** [comment]
Got it. Thanks for the help here @navba-MSFT. I finally understood that even though I wanted to manage just the sql server audit settings, I have to do that through the master database attached to the sql server. Apologies for the confusion
