### ISSUE TITLE
Support for Branches section in Virtual Hub Route Table

### ISSUE THREAD

**Issue by ritikgupta3** [Azure/azure-rest-api-specs#22200]
the original issue which was closed due to the author's late reply:
https://github.com/Azure/azure-rest-api-specs/issues/21136

The API doesn't appear to have support for the properties in "Branches" in Virtual Hub Route Table that are available via the portal:

![image](https://user-images.githubusercontent.com/117618887/212601664-61db19f4-d93e-4d2c-afd9-5f0bf9aa536c.png)

Basically, we want to change this setting, currently, there seems to be no way to do so.
Documentation referenced: https://learn.microsoft.com/en-us/rest/api/virtualwan/hub-route-tables/create-or-update?tabs=HTTP

**Comment by navba-MSFT** [comment]
@ritikgupta3 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ritikgupta3 **_More Info:_**
Please refer this:  https://github.com/Azure/azure-rest-api-specs/blob/13d172c85dac78b65d023dcd95097c383e38c048/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/virtualWan.json#L5854

See the documentation here: https://learn.microsoft.com/en-us/rest/api/virtualwan/virtual-wans/create-or-update?tabs=HTTP

**Comment by mlcooper** [comment]
@navba-MSFT my network engineer colleague and I looked at this documentation and we do NOT see an API endpoint to configure this setting.

**Comment by navba-MSFT** [comment]
@mlcooper Thanks for getting back and clarifying the ask. While I tried to reproduce the setting changes at my end and found the below REST API was being called while I tried to **Edit** the VirtualHub RouteTable configurations:

**POST** https://management.azure.com/subscriptions/XXXXXXXXX/resourceGroups/navbatest/providers/Microsoft.Network/virtualHubs/navbavhub/effectiveRoutes?api-version=2022-07-01 HTTP/1.1
Content-Length: 214
Authorization: Bearer eyJ0eXAiOiXXXXXXX
Content-Type: application/json

**Request Body:**
{"VirtualWanResourceType":"RouteTable","ResourceId":"/subscriptions/XXXX/resourceGroups/MyRGName/providers/Microsoft.Network/virtualHubs/MyVHub/hubRouteTables/defaultRouteTable"}

https://github.com/Azure/azure-rest-api-specs/blob/2d9846d81852452cf10270b18329ac382a881bf7/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/virtualWan.json#L5854

**Comment by mlcooper** [comment]
While this is indeed a `POST`, the documentation description [here](https://learn.microsoft.com/en-us/rest/api/virtualwan/virtual-hubs/get-effective-virtual-hub-routes?tabs=HTTP) says:

>Gets the effective routes configured for the Virtual Hub resource or the specified resource.

It does not appear that it allows you to set or configure anything.

**Comment by navba-MSFT** [comment]
@mlcooper That's interesting. Thanks for sharing this with us. I have reached out to the Product Owners to get a clarity on the REST API that is invoked for the below setting. I will keep you posted.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/57353862/214212159-df9ff9cf-d157-4ead-92a7-abbef2273200.png">

**Comment by navba-MSFT** [comment]
@ritikgupta3 @mlcooper I have heard back from the Product Owners. There is no API call to batch update propagations of branches etc. connected to Virtual Hub. This portal blade just provides customer a way to batch update the propagations of all branches connected to Virtual Hub and we need this because all branches connected to hub must have the same routing configuration. Please let me know if you have any follow-up questions on this.

**Comment by navba-MSFT** [comment]
@ritikgupta3 @mlcooper I hope you had a chance to look at my above comment. Could you please let me know if you have any follow-up questions. Awaiting your reply.

**Comment by mlcooper** [comment]
I still don't really understand why an API endpoint would not be provided to update the propagations. We have more than one vHub spread across several Azure regions, all created via automation (Terraform) and we may want the propagation setting to be different from one vHub to another. It is not ideal to have to configure this setting manually.

**Comment by navba-MSFT** [comment]
@mlcooper I think there is some confusion. Sending you the detailed explanation to clarify.

You can update the associations and propagations of each branch individually. See this Terrafom link [azurerm_vpn_gateway_connection | Resources | hashicorp/azurerm | Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway_connection) (routing section).  

For each of these branch connections, you can define the associations and propagations as code. Note that you would want to ensure all branches connected to the same hub have the same routing configuration (otherwise you may experience unexpected behaviors). If you were to modify the propagations of 5 branches, you would need to perform 5 Terrafom updates in your code.

The portal option sort of parallelizes/streamlines updates to multiple branches by using an ARM template (or similar mechanism) to update all the associations and propagations at once. This is still done at a per-connection level from a deployment perspective- there isn’t a backdoor short cut we are able to do to update everything using a single API call/ARM deployment. So if you have 5 branches, this is translated to 5 separate updates on each connection. Hope this clarifies.

**Comment by ritikgupta3** [comment]
@navba-MSFT , 
<img width="763" alt="Screenshot 2023-02-02 at 12 24 08 PM" src="https://user-images.githubusercontent.com/117618887/216253110-1103be25-d97f-4898-a4e8-43330104dc2a.png">


All connections are fine but we need to toggle this setting to "YES". How can we do that using code (either terraform or API)?

We couldn't find a way to do it yet. Can you please suggest one?

**Comment by navba-MSFT** [comment]
@ritikgupta3 Like the mentioned above there is no API made available. If there is no API there is no terraform or SDK that can do it. Hope that answers it.

**Comment by mlcooper** [comment]
@navba-MSFT I need to change this setting to `Yes` in the `Default` route table of the vHub. I don't think I was clear before that this is in the `Default` route table of the vHub. 

Can you please let us know if Azure could create an API for this?

**Comment by navba-MSFT** [comment]
@mlcooper Thanks for your reply. As mentioned above there is no API made available to toggle (yes/no) this setting.

**Comment by mlcooper** [comment]
@navba-MSFT Above you mention that you can update propagations of each branch individually with `azurerm_vpn_gateway`, however we do not have an VPN's in our architecture. We only use ExpressRoute for connectivity.
