### ISSUE TITLE
Recommendation for PUT/PATCH model definition in swagger?

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#2252]
Some questions come up regularly on how to model PUT/PATCH models in swagger, due to violations detected by linter and restrictions from service side operations. 
Could we write down recommendations for modeling these scenarios in swagger to become more consistent?
Here are cases I've seen:
 - Sharing models for PATCH and PUT may need relaxing "require" properties, as properties are required on PUT but not on PATCH. From PUT perspective, this results in an SDK that does not require the properties that are required from the service side, on the other hand, it allows sharing the models defined for the operations. (see reference example: https://github.com/Azure/azure-rest-api-specs/pull/2242#discussion_r160774760) - FYI - @jianghaolu 
 - [TrackedResourcePathOperation](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3026-trackedresourcepatchoperation) gets reported for body parameter of create operation, even though the parameters model is not really a resource (the response of the operation is), the models between body and response are not shared and the parameters model inherits from Resource, so ends up with a suppression for the rule. (see reference example https://github.com/Azure/azure-rest-api-specs/pull/2229#discussion_r160771335)

Thoughts? @johanste @amarzavery @salameer @kirthik

**Comment by johanste** [comment]
I typically give the recommendation to not share the same model type in the swagger document. By sharing the model, you end up with a) loser constraints on the PUT operation and b) additional properties that are not mutable in the PATCH operation. Both of which are misleading. 

Given the semantics of the PATCH operation (only transmit the things you want to change), there are less reasons to do a GET first to get the model. If you want to do a conditional update of an existing resource, then it is still supported if you follow the recommendation to have the response body for GET be the same/interchangeable for the request body of the PUT. For fire-and-forget kind of updates (only do a PATCH), using a different, more targeted model, does, in my opinion, simplify the API rather than complicate it.

Depending on the exact payloads, you may be able to share a common base model that includes the mutable, non-required properties for PATCH and one that does an allOf the base model for the PUT which adds required/non-mutable properties. 

Also, if PATCH supports UPSERT semantics, then the payload must allow any required properties as well as non-mutable properties in order to support create-if-not-exists. 

With regards to the TrackedResourcePathOperation question, I would assume that the violation would be generated based on the response body of an ARM path rather than on the request body. If the model types for the request and the response are different, then we should have the general API suggestion warning on using the same model type if at all possible.

Just my SEK 0,02
