### ISSUE TITLE
SQL Server Auditing Settings - Create Or Update Issue

### ISSUE THREAD

**Issue by levgoronshteyn** [Azure/azure-rest-api-specs#22531]
When reviewing the SQL Server Audit Settings, i do not see any way to specify Event Hub or Log Analytics to be used.

https://learn.microsoft.com/en-us/rest/api/sql/2017-03-01-preview/server-auditing-settings/create-or-update?tabs=HTTP

The only way to use this API is for blob storage but in the Azure Portal i can select Log Analytics and\or Event Hub.
![Screenshot 2023-02-09 at 11 35 40 AM](https://user-images.githubusercontent.com/119378222/217878155-21bf2852-36ea-4f0d-a37f-5d8fc026c52f.png)

Could the documentation be updated with how to enable audit setting with log analytics and\or event hub.

**Comment by navba-MSFT** [comment]
@levgoronshteyn Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by levgoronshteyn** [comment]
Hi @navba-MSFT,

Thank you for the reply but from the looks of it, it is 2 different APIs, my question is more around if Server auditing will have the same functionality as Audit settings.

At the moment we would have to call 2 different APIs to accomplish the tasks.

**Comment by navba-MSFT** [comment]
@levgoronshteyn Yes this SQL Server auditing is same as the auditing setting. 

**More Info:**
Managing and Analyzing audit logs are explained [**here**](https://learn.microsoft.com/en-us/azure/azure-sql/database/auditing-overview?view=azuresql).
The audit log format is explained **[here](https://learn.microsoft.com/en-us/azure/azure-sql/database/audit-log-format?view=azuresql)**. 

As mentioned earlier, you will have to call 2 APIs:  [REST API 1](https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP) and [REST API 2](https://learn.microsoft.com/en-us/rest/api/sql/2021-08-01-preview/server-blob-auditing-policies/create-or-update) to accomplish this task. This is by design.
