### ISSUE TITLE
Microsoft.Insights/diagnosticSettings logs: "Diagnostic setting does not support mix of log category and log category group."

### ISSUE THREAD

**Issue by juanjojulian** [Azure/azure-rest-api-specs#22719]
Good afternoon, I'm getting the following error message:

`"Diagnostic setting does not support mix of log category and log category group."`

When I try to apply (PUT) the following code to the API:

```
{
  "properties": {
    "logAnalyticsDestinationType": "AzureDiagnostics",
    "logs": [
      {
        "categoryGroup": "allLogs",
        "enabled": true,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      },
      {
        "category": "NetworkSecurityGroupRuleCounter",
        "categoryGroup": "",
        "enabled": false,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      }
    ],
    "metrics": [],
    "storageAccountId": "/subscriptions/00000-000-0000-000c-88827/resourceGroups/terraform-westeurope-rg/providers/Microsoft.Storage/storageAccounts/myesa"
  }
}
```

I believe the API is considering both [log blocks](https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP#logsettings) as enabled and triggering an error because both `category` and `categoryGroup` are fulfilled. Please note that the first block, the only one enabled, doesn't even have a `category` attribute.

**Comment by navba-MSFT** [comment]
@juanjojulian Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@juanjojulian It looks like the issue with your Request Body, since you're mixing log categories and log category groups in the same "logs" array.

As the error message you received states, the diagnostic settings API does not support a mix of log categories and log category groups in the same "logs" array. You will need to separate them out into separate arrays.

Here's an example of what the request body should look like if you have both log categories and log category groups to configure:

```
"logs": [
  {
    "category": "AppServiceHTTPLogs",
    "enabled": true,
    "retentionPolicy": {
      "days": 30,
      "enabled": true
    }
  }
],
"logAnalyticsDestinationType": "Dedicated",
"logAnalyticsDestinationProperties": {
  "workspaceResourceId": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}"
},
"metrics": [
  {
    "category": "AllMetrics",
    "enabled": true,
    "retentionPolicy": {
      "days": 7,
      "enabled": true
    }
  }
],
"workspaceId": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.operationalinsights/workspaces/{workspaceName}",
"metricSettings": [
  {
    "category": "AllMetrics",
    "enabled": true,
    "retentionPolicy": {
      "days": 0,
      "enabled": false
    }
  },
  {
    "category": "NetworkSecurityGroupFlowEvent",
    "enabled": true,
    "retentionPolicy": {
      "days": 7,
      "enabled": true
    }
  }
]
```
In this example, the "metricSettings" array contains two objects, one that specifies a log category group ("AllMetrics"), and one that specifies a log category ("NetworkSecurityGroupFlowEvent").

**Comment by juanjojulian** [comment]
Thanks for your answer @navba-MSFT but I don't think is the same case as mine. What I'm doing here is disabling `NetworkSecurityGroupRuleCounter` (category) log block and enabling `allLogs` (categoryGroup) log block. My understanding is that the API should take into account that one block is disabled and ignore it otherwise I don't understand what the "enabled" attribute in the log block is for.

![CleanShot 2023-02-24 at 07 26 58@2x](https://user-images.githubusercontent.com/43988825/221107990-fd06052d-c0ca-4109-8973-4bc43c454e48.png)

It's true that I could just remove the entire `category` log block instead of disabling it and it works, but still don't understand what is the `enabled` attribute for.

```
{
  "properties": {
    "logAnalyticsDestinationType": "AzureDiagnostics",
    "logs": [
      {
        "category": null,
        "categoryGroup": "allLogs",
        "enabled": true,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      }
    ],
    "metrics": [],
    "storageAccountId": "/subscriptions/1XX-XXX-XXXX-XXXb/resourceGroups/terraform-westeurope-rg/providers/Microsoft.Storage/storageAccounts/mytesa"
  }
}
```

**Comment by navba-MSFT** [comment]
@juanjojulian Thanks for clarifying. The error message `"Diagnostic setting does not support mix of log category and log category group."` you received indicates that the API request failed because you mixed log category and log category group settings.

To resolve this error, you can modify your request body to either use only log categories or only log category groups, but not both. For example, you could remove the "categoryGroup" property from the first log setting and replace it with a "category" property that specifies the log category to collect.


Here's an example request body that only uses log categories:

```
{
  "properties": {
    "logAnalyticsDestinationType": "AzureDiagnostics",
    "logs": [
      {
        "category": "AllMetrics",
        "enabled": true,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      },
      {
        "category": "NetworkSecurityGroupRuleCounter",
        "enabled": false,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      }
    ],
    "metrics": [],
    "storageAccountId": "/subscriptions/00000-000-0000-000c-88827/resourceGroups/terraform-westeurope-rg/providers/Microsoft.Storage/storageAccounts/myesa"
  }
}

```

Alternatively, here's an example request body that only uses log category groups:

```
{
  "properties": {
    "logAnalyticsDestinationType": "AzureDiagnostics",
    "logs": [
      {
        "categoryGroup": "AllLogs",
        "enabled": true,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      },
      {
        "categoryGroup": "NsgFlowLogs",
        "enabled": false,
        "retentionPolicy": {
          "days": 0,
          "enabled": false
        }
      }
    ],
    "metrics": [],
    "storageAccountId": "/subscriptions/00000-000-0000-000c-88827/resourceGroups/terraform-westeurope-rg/providers/Microsoft.Storage/storageAccounts/myesa"
  }
}

```
I hope this helps!

**Comment by navba-MSFT** [comment]
@juanjojulian I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by juanjojulian** [comment]
Hi @navba-MSFT I have the impression that you didn't understood what I was trying to do, I wanted to **disable** the block with the `category` attribute and **enable** the block with the `categoryGroup` attribute. I understand that as one block is disabled the restriction that forbid `mix of log category and log category group` should not apply because it is disabled. Otherwise I don't understand the reason for having an attribute (enabled) to enable and disable a block.

**Comment by navba-MSFT** [comment]
@juanjojulian Thanks for clarifying the ask. I am adding the Service team to look into this further.

@AzMonEssential Could you please look into this once you get a chance ? Thanks.

**Comment by nkiest** [comment]
Our rules restrict having categories and category groups in the same diagnostic settings, regardless of "enabled". You can view "enabled: false" as an option to keep the setting stored, while temporarily disabling it. The restriction about mixing and matching categories and categoryGroups still applies, because of how we store the information.

Given that the UX and other interfaces don't show "enabled: false", I would recommend just deleting logs you do not want to collect for the sake of readability and consistency. We can't remove 'enabled" without breaking existing contracts, however, so it stays for backwards compatibility.

**Comment by juanjojulian** [comment]
> Our rules restrict having categories and category groups in the same diagnostic settings, regardless of "enabled". You can view "enabled: false" as an option to keep the setting stored, while temporarily disabling it. The restriction about mixing and matching categories and categoryGroups still applies, because of how we store the information.
> 
> Given that the UX and other interfaces don't show "enabled: false", I would recommend just deleting logs you do not want to collect for the sake of readability and consistency. We can't remove 'enabled" without breaking existing contracts, however, so it stays for backwards compatibility.

Thanks @nkiest understood, I'm going to close the issue then.
