### ISSUE TITLE
questions about the api version

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-rest-api-specs#2274]
1. Will the older api versions be deprecated in future? For example, the stable version `2015-06-15` or the preview version `2016-04-30-preview`.
2. To keep stable, we don't want to upgrade the api version in our software if there are no strong reasons. Now, we are using `2015-06-15` for several services (e.g. SRP). What's the benefit of upgrading api version? (stability, performance?) Any specific suggestions to upgrade the api versions? If there are some best practice, maybe it's better to document them.

**Comment by bingosummer** [comment]
@sergey-shandar any ideas?

**Comment by yungezz** [comment]
normally we'll suggest to upgrade to lastest version, because latest version contains latest features/functionalities. about old api deprecation, it's a complex process and depending on each azure service plan, there's no general answer on whether some version will be deprecated. Hope this helps. close the issue for now. Feel free to create new one or reopen if any furthur questions.
