### ISSUE TITLE
Two swagger files in the same folder

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#229]
This dir contains two Swagger files:
https://github.com/Azure/azure-rest-api-specs/tree/master/arm-compute/2016-03-30/swagger
Is it intended?
I'm asking, because all other folders have only one Swagger file per dir.

**Comment by amarzavery** [comment]
@IvanGoncharov - Each swagger spec is tied to one version a.k.a api-version of the service. The compute RP comprises of small services where each service has its own api-version. Hence, each sub-service has its own swagger spec. All of them are tied together using this [composite spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/compositeComputeClient.json) and are packaged together into one compute client library. This makes it easier for customers to download one nuget/npm/pip/maven/gem package rather than installing individual packages for each sub service.

**Comment by IvanGoncharov** [comment]
@amarzavery Thank you for quick response.
I think it's worth to be mentioned in README.

**Comment by amarzavery** [comment]
@IvanGoncharov - Thanks for the feedback. We shall update the README.
