### ISSUE TITLE
[Microsoft.CostManagement] Query_Usage missing pagination in specification

### ISSUE THREAD

**Issue by jkroepke** [Azure/azure-rest-api-specs#23405]
Hi,

The API REST Call `$scope/providers/Microsoft.CostManagement/query` supports pagination, but its currently specified on the API docs.

I could re-validate this by manually calling the API with curl:

```
$ curl https://management.azure.com/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$top=2 | jq .properties.nextLink
https://management.azure.com/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/providers/Microsoft.CostManagement/query?api-version=2021-10-01&$top=2&$skiptoken=AQAAAA%3D%3D
```

My answer contains more than 2 results and a nextLink with skip token provided by the API.

In conclusion, since the API Docs doesn't have this documented, downstream SDKs are not supporting pagination on that API Call, too. This results into issues that only 1000 elements can be queried.

- https://github.com/MicrosoftDocs/azure-docs/issues/40454
- https://github.com/Azure/azure-sdk-for-python/issues/23175
- https://github.com/Azure/azure-sdk-for-go/issues/19002
- https://github.com/Azure/azure-rest-api-specs/issues/22528

**Comment by navba-MSFT** [comment]
@jkroepke Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please check if the below workaround sample code helps ?

https://gist.github.com/JoramM/c0538593c80822e37f6cd6d0d2c0c65f

**Comment by navba-MSFT** [comment]
@jkroepke I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jkroepke I am discussing this with the Product Owners, I will update once I hear from them.

**Comment by jkroepke** [comment]
@weidongxu-microsoft @navba-MSFT Maybe you can bundle your power here.

Thanks a lot for moving forward this!

**Comment by weidongxu-microsoft** [comment]
The problem is the design of the service response does not match the agreed pageable solution.  https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-pageable
Hence SDK not able to support.

The expected response for a pageable would be (pagination on `value`)
```yaml
value: [...]
nextLink: https://...
```

But cost-management returns this
```yaml
id: ...
name: ...
type: ...
properties:
  nextLink: https://
  columns: [...]
  rows: [...]
```

And they expect the pagination happens on the `properties.rows`.

One can see the 2 response is not compatible at all.

**Comment by jkroepke** [comment]
Thanks for the clarifications!

> One solution I can think of, is to ask backend to add "skipToken" parameter to API, and include "skipToken" in response if "nextLink" available.

If you take a look at https://github.com/Azure/azure-rest-api-specs/issues/23405#issuecomment-1505064440, the API already support `$skipToken` and behavior you present (like getting the new page) is already present.

Seems like full paginations exists, but not in a standard Azure API way.

**Comment by weidongxu-microsoft** [comment]
> Thanks for the clarifications!
> 
> > One solution I can think of, is to ask backend to add "skipToken" parameter to API, and include "skipToken" in response if "nextLink" available.
> 
> If you take a look at [#23405 (comment)](https://github.com/Azure/azure-rest-api-specs/issues/23405#issuecomment-1505064440), the API already support `$skipToken` and behavior you present (like getting the new page) is already present.
> 
> Seems like full paginations exists, but not in a standard Azure API way.

Yes. It exists in backend, but it is not exposed to swagger, and hence SDK won't have it in API.

Also current the skipToken can only be extracted from nextLink in response, which is not very simple for user not familiar with URL parsing and escaping.

**Comment by navba-MSFT** [comment]
@weidongxu-microsoft I have an active email thread going with the Service team. I will loop you there for awareness. Currently I am waiting for their reply.

**Comment by navba-MSFT** [comment]
@jkroepke I had a discussion with the Cost Management Query API product owners. Sharing the update here.

Most ARM APIs deal with Creating/Updating/Getting/Deleting an azure resource, so a get response is usually in the form of a “value” array of objects that represent the resource(s) information.
Example:

![image](https://user-images.githubusercontent.com/57353862/234170400-d17d4f8e-41a9-4cba-bea1-99665f9894d5.png)

In our case, we do not do the above operations on a resource, we simply fetch the aggregated cost of a resource based o what the customer specifies (and I am sure, as customers of the API, you already know that). 

Hence, our response in unconventional: 

![image](https://user-images.githubusercontent.com/57353862/234170744-b2cfe88e-7617-4677-8618-adfc854d5317.png)

So due to the above we **cannot** add the `x-ms-pageable` field in the [REST API specs swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L950-L959). And since this is not available in the swagger, the SDK cannot provide this functionality.

So in short, the ONLY workaround here is to invoke the [Cost management query API](https://learn.microsoft.com/en-us/rest/api/cost-management/query), Get the NextLink marker and enumerate through it until the provided nextLink is null. Samples are [here ](https://gist.github.com/JoramM/c0538593c80822e37f6cd6d0d2c0c65f) and [here](https://github.com/jkroepke/homelab/blob/571c16491f2f2205a3d52e5ce046aa7adfb8a1d2/go/azure-cost-query-pagination/main.go). Hope this helps.
