### ISSUE TITLE
Send_email off/on working in past 3 day

### ISSUE THREAD

**Issue by sb185296** [Azure/azure-rest-api-specs#23687]
hi team ,

in the past 3 days we are working with send email.
the Logic app failed to run on 

```
Failed to start a run of logic app emailtest-workflowtest. The template language expression evaluation failed: 'The execution of template trigger 'When_a_resource_event_occurs' failed: the result of the evaluation of 'splitOn' expression '@triggerBody()' is of type 'Null'. The result must be a valid array.'
```

we are using - 
Send_email_(Preview) "api-version": "2021-10-01-preview"

i try to switch to 2023-01-15-preview and to 2023-03-31

get the same problem

![image](https://user-images.githubusercontent.com/66299621/233977557-f5140c6d-79f3-48a6-baef-6f11c35d3ff1.png)

what i am missing?

thanks

**Comment by sb185296** [comment]
now its back on working 👍 
so what is the problem

**Comment by navba-MSFT** [comment]
> now its back on working 👍 so what is the problem

@sb185296 Thanks for reaching out to us and reporting this issue. I am glad that the issue is now resolved. 
The error message indicates that the `splitOn `expression in the `When_a_resource_event_occurs` trigger of your Logic App is evaluating to null, which is causing the trigger to fail.

The splitOn expression is used to split the input data into an array of objects. If the input data is not in the expected format, the splitOn expression may evaluate to null.

To troubleshoot this issue, you can try the following steps:
- Check the input data for the When_a_resource_event_occurs trigger to ensure that it is in the expected format. The input data should be an array of objects.
- Check the splitOn expression in the trigger to ensure that it is correctly splitting the input data into an array of objects. The splitOn expression should return an array of objects.
- If the input data is not in the expected format, you may need to modify the trigger to handle the input data correctly.
- If the splitOn expression is not correctly splitting the input data into an array of objects, you may need to modify the expression to correctly split the input data.

Here's an example of a `splitOn `expression that splits the input data into an array of objects:

```
split(triggerBody()?['value'], ';')
In this example, the splitOn expression splits the input data into an array of objects using the semicolon (;) as the delimiter.
```

Hope this helps.

**Comment by navba-MSFT** [comment]
@sb185296 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Ensure that the above suggestions are followed to avoid the issue from re-occurring. Please feel free to reopen this issue if you need any further assistance. We would be happy to help.

**Comment by sb185296** [comment]
hi team
thanks alot for that
we will look on that and we update


but from what we see last week that its not work with out any body or somting like that
