### ISSUE TITLE
[azure-mgmt-costmanagement] Is CostmanagementClient.query.usage support pagination?

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-rest-api-specs#24284]
- **Package Name**:  azure-mgmt-costmangement
- **Package Version**:  4.0.0
- **Operating System**: Mac OS 
- **Python Version**: 3.8

**Describe the bug**

I'm not certain if this is a bug, 
but when I attempt to retrieve the next response from CostManagementClient.query.usage() and the response exceeds 5000 rows, the result contains a next_link property. 
I would like to understand how to use this value for obtaining the next set of results.

**To Reproduce**
1. Here is the test code that I used.
```
import os
from azure.mgmt.costmanagement import CostManagementClient
from azure.identity import DefaultAzureCredential

os.environ["AZURE_TENANT_ID"] = ''
os.environ["AZURE_CLIENT_ID"] = ''
os.environ["AZURE_CLIENT_SECRET"] = ''

subscription_id = ''

credential = DefaultAzureCredential()

cost_client = CostManagementClient(credential=credential, subscription_id=subscription_id)

scope = ''

parameters = {
  'type': 'ActualCost', 
  'dataSet': {
    'granularity': 'Daily', 
    'aggregation': {
      'totalCost': {'name': 'Cost', 'function': 'Sum'},
      "UsageQuantity": {"name": "UsageQuantity", "function": "Sum"}
    },
    'grouping': [
        {'type': 'Dimension', 'name': 'ResourceGroup'}, 
        {'type': 'Dimension', 'name': 'ResourceType'}, 
        {'type': 'Dimension', 'name': 'ResourceId'},
        {'type': 'Dimension', 'name': 'ResourceLocation'}, 
        {'type': 'Dimension', 'name': 'SubscriptionId'}, 
        {'type': 'Dimension', 'name': 'SubscriptionName'}, 
        {'type': 'Dimension', 'name': 'MeterCategory'}, 
        {'type': 'Dimension', 'name': 'Meter'}, 
        {'type': 'Dimension', 'name': 'ServiceName'}, 
        {'type': 'Dimension', 'name': 'UnitOfMeasure'}
]
  }, 
  'timeframe': 'Custom', 
  'timePeriod':
  {'from': '2023-05-01T00:00:00.000Z',
  'to': '2023-05-29T23:59:59.000Z'
    
  }
}
```
2. The result should contain more than 5000 rows.
3. In the response result, you can obtain the next_link value.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by navba-MSFT** [comment]
@ImMin5 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. I had a discussion with the Cost Management Query API product owners. Sharing the update here.

Most ARM APIs deal with Creating/Updating/Getting/Deleting an azure resource, so a get response is usually in the form of a “value” array of objects that represent the resource(s) information.
Example:

<img width="341" alt="image" src="https://github.com/Azure/azure-rest-api-specs/assets/57353862/903b394b-89e8-4a2f-95cb-bc1a389a07a2">


In our case, we do not do the above operations on a resource, we simply fetch the aggregated cost of a resource based o what the customer specifies (and I am sure, as customers of the API, you already know that).

Hence, our response in unconventional:

<img width="382" alt="image" src="https://github.com/Azure/azure-rest-api-specs/assets/57353862/d9f7a0fb-933f-4c4e-a574-57ef707425d9">

So due to the above we cannot add the x-ms-pageable field in the [REST API specs swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L950-L959). And since this is not available in the swagger, the SDK cannot provide this functionality.

So in short, the ONLY workaround here is to invoke the [Cost management query API](https://learn.microsoft.com/en-us/rest/api/cost-management/query), Get the NextLink marker and enumerate through it until the provided nextLink is null. Samples are [here ](https://gist.github.com/JoramM/c0538593c80822e37f6cd6d0d2c0c65f)and [here](https://github.com/jkroepke/homelab/blob/571c16491f2f2205a3d52e5ce046aa7adfb8a1d2/go/azure-cost-query-pagination/main.go). Hope this helps.

**Comment by navba-MSFT** [comment]
@ImMin5 Hope you had a chance to look at my above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by ImMin5** [comment]
@navba-MSFT Thanks for your comment.
The sample that gave me was helpful for me.

First, do you have any plans to add a parameter like `skipToken` in REST api to the Azure Cost Management SDK? Currently, I can use the REST API, but I would like to use the SDK in the future.

And lastly, if I make calls to the Cost Management API, does Azure charge for that? I would like to learn more about this, but I couldn't find any documentation regarding it.
