### ISSUE TITLE
Unable to import Azure OpenAI v2023-05-15 to Azure API Management (APIM)

### ISSUE THREAD

**Issue by ericthomas1** [Azure/azure-rest-api-specs#24450]
Hello,

When trying to import the [latest OpenAI inference spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2022-12-01/inference.json), it fails due to, what appears be, the `{endpoint}` variable on the `servers` `url` value. 

**Example**:
- Trying to upload spec from the [raw url](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/inference.json) or from file results in the error:
    - ![image](https://github.com/Azure/azure-rest-api-specs/assets/42788729/aa12f3cd-722c-4b4b-9cc5-be0407247b4e)
    - `One or more fields container incorrect values: Invalid value of the Web service url.`
- The term `url` is only found 2x in the spec. 
- Removing the `{endpoint}` variable and putting in the actual endpoint of my Azure OpenAI resource allowed for the import of the spec:
    - Changed this:
        - ![image](https://github.com/Azure/azure-rest-api-specs/assets/42788729/711c260a-9d07-44c9-94fc-956f86015b72)
    - To this:
        - ![image](https://github.com/Azure/azure-rest-api-specs/assets/42788729/8ed15c28-d5de-48f6-9c74-49f06045ed10)
    - Then the import was successful.

Not sure if its a spec issue or an APIM issue. Hope this helps.

**Comment by navba-MSFT** [comment]
@ericthomas1 Thanks for reaching out to us and reporting this issue. The `url` field expects the right endpoint of your open AI service. Therefore the **placeholder** `{endpoint}` is added.

```
"servers": [
    {
      "url": "https://{endpoint}/openai",
      "variables": {
        "endpoint": {
          "default": "your-resource-name.openai.azure.com"
        }
      }
    }
  ]
```
If you directly link to this rest api specs from API without updating the placeholder it is bound to fail. So the error `Invalid value of the Web service url.` is expected. As you mentioned above, adding the right open ai endpoint is the right approach for this. This is neither  a spec issue or an APIM issue. But an expected behavior.

**Comment by ericthomas1** [comment]
Ah, ok. My apologies. This is the first time I'm using OpenAPI definitions. I was following some instructions and the step of adding my own endpoint wasn't part of them. 

Thanks for the guidance.

**Comment by jefferygannon** [comment]
ok this makes it impossible to use create this API via bicep or other IaC right?
