### ISSUE TITLE
`PaloAltoNetworks` Get on a non-existant LocalRule results in a `400`

### ISSUE THREAD

**Issue by jackofallops** [Azure/azure-rest-api-specs#24697]
Performing a `Get` on a Local Rule that does not exist results in an unexpected `400` error with the message:
`unexpected status 400 with error: PriorityMustBeValidNumber: Priority given must be a valid number between 1-10000`

This should return a `404`.

API Version: `2022-08-29`
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29/PaloAltoNetworks.Cloudngfw.json#L3889

**Comment by jackofallops** [comment]
After further investigation, it seems the Spec maybe misleading here.  The Spec has `ruleName` marked as required (https://github.com/Azure/azure-rest-api-specs/blob/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29/PaloAltoNetworks.Cloudngfw.json#L6700) and not `priority` and the ID takes the priority as the final segment of the ID and not updatable. 

Ca this be clarified/corrected?

**Comment by rheajain** [comment]
The unique identifier used in the Resource ID for Local Rules is the priority and not the rule name. However, a ruleName is also a mandatory field. This is by design.
In the properties of Local Rules it is not marked as a mandatory parameter as we do not expect the user to provide the priority for create/ update calls in two places- URL path and payload. Instead, we have marked priority as a readonly attribute, as it is part of the GET response.
[azure-rest-api-specs/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29/PaloAltoNetworks.Cloudngfw.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29/PaloAltoNetworks.Cloudngfw.json#L6612)

**Comment by navba-MSFT** [comment]
@jackofallops Please let us know if you had a chance to look at the above comment. If you have any follow-up questions, please do let us know.

**Comment by jackofallops** [comment]
Hi @navba-MSFT - I'm satisfied with the comment and have discussed this off-line with @rheajain, I'll close this now. Thanks!
