### ISSUE TITLE
APIM SystemAssigned managed identity unable to get certificate stored in keyvault using Azure RBAC permission model

### ISSUE THREAD

**Issue by dewolfs** [Azure/azure-rest-api-specs#25045]
Hi,

I want to add custom domains to API Management that is deployed using internal VNET mode.  
The keyVault using Azure RBAC permission model contains 3 certificates for the 3 custom hostnames of APIM.

Part of the APIM **hostnameConfiguration** is to link to the certificate valid for the custom hostname.

The APIM System assigned managed identity has ''Key Vault Administrator" (https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#azure-built-in-roles-for-key-vault-data-plane-operations) role assigned on the KeyVault resource.

I'm using the following Bicep template:

```
resource apim 'Microsoft.ApiManagement/service@2023-03-01-preview' = {
  name: 'apim-999-aha'
  location: location
  sku: {
    capacity: 1
    name: sku
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    hostnameConfigurations: [
      {
        type: 'DeveloperPortal'
        hostName: apimDeveloperHostName
        keyVaultId: apimDeveloperKeyVaultId
        certificate: {
          expiry: apimDeveloperExpiry
          thumbprint: apimDeveloperThumbprint
          subject: apimDeveloperSubject
        }
        defaultSslBinding: false
        negotiateClientCertificate: false
      }
    ]
    publicIpAddressId: apim-pip
    publisherEmail: publisherEmail
    publisherName: publisherName
    virtualNetworkConfiguration: {
      subnetResourceId: subnetRef.id
    }
    virtualNetworkType: 'Internal'
  }
}
```

When executing the above template, I get the following error:

_Check if Managed Identity of Type: SystemAssigned, ClientId: xxxxx-xxxx-xxxx-3558fc1628d0 and ObjectId:  has GET permissions on secrets in the KeyVault Access Policies_

Does this mean that APIM system managed identity can only retrieve certificates inside a KeyVault which has the legacy Access Policies permission model (https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-access-policy)?

**Comment by navba-MSFT** [comment]
@dewolfs Apologies for the late reply. Thanks for reaching out to us and reporting this issue.  The error message indicates that the APIM system managed identity does not have the required permissions to retrieve the certificates from the KeyVault. The error message suggests that the managed identity needs to have GET permissions on secrets in the KeyVault Access Policies.

To resolve this issue,  you need to ensure that the APIM system managed identity has the required permissions to retrieve the certificates from the KeyVault. I understand that you have already assigned the 'Key Vault Administrator' role to the managed identity, which should provide the necessary permissions. However, the error message suggests that the managed identity does not have the required permissions.

One possible reason for this issue is that the KeyVault is using the Azure RBAC permission model, which requires the managed identity to have the appropriate permissions assigned explicitly. You can try assigning the '[Secrets User](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#key-vault-secrets-user)' role to the managed identity explicitly to provide the necessary permissions to retrieve the certificates from the KeyVault.

Here is an example of how to assign the 'Secrets User' role to the managed identity using Azure CLI:

> **az keyvault set-policy --name <keyvault-name> --object-id <managed-identity-object-id> --secret-permissions get list --subscription <subscription-id>**

This command assigns the 'Secrets User' role to the managed identity with the specified object ID for the specified KeyVault. The managed identity will have the 'get' and 'list' permissions on secrets in the KeyVault.

Alternatively, you can try using the legacy Access Policies permission model for the KeyVault, which should allow the managed identity to retrieve the certificates without requiring explicit permissions and check if that helps:

Here is an example of how to enable the legacy Access Policies permission model for the KeyVault using Azure PowerShell:

> **Set-AzKeyVaultAccessPolicy -VaultName <keyvault-name> -EnabledForDeployment $true**

This command enables the legacy Access Policies permission model for the specified KeyVault. Hope this helps.

**Comment by navba-MSFT** [comment]
@dewolfs I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by dewolfs** [comment]
Hi @navba-MSFT , thank you for your reply.  I did some additional investigation and got it working after all.  However it had nothing todo with missing access of the APIM system-managed identity to the keyvault.

I had to create 2 separate Bicep deployments/files:
1. file-1.bicep: this template contains the basic APIM config without **_hostnameConfigurations_** but with role assignment of the system-managed identity on the keyVault.
2. file-2.bicep: this template contains the same APIM config as file-1.bicep but with **_hostnameConfigurations_**.

If you put all the parameters in a single bicep template, it won't work.  Looks like you will have a race condition and end up with the error in this issue.  Tried with implicit and explicit dependsOn but did not had any luck.

This is an unfortunate way-of-working causing duplicate code and also it takes a long time to complete (this is to blame to the APIM resource, although it's a PaaS resource in the background it's a VMSS).
