### ISSUE TITLE
Microsoft.Billing consumption API missing last day of every month

### ISSUE THREAD

**Issue by william-inf** [Azure/azure-rest-api-specs#2951]
I am having some trouble getting back a full window of charges.  

My problem starts with getting the invoice periods.

I have noticed in your Invoice API your dates are:

`"invoicePeriodStartDate": "2017-01-01","invoicePeriodEndDate": "2017-02-01"` (a FULL month)

I receive back 

`invoicePeriodEndDate":"2017-05-31", "invoicePeriodStartDate":"2017-05-01"`  

Moreover, I only receive one billingPeriodId back, not multiple as above example in this repo.
(For reference, both the billingPeriods and Invoice list APIs return the same dates)

So using the following API ("/subscriptions/{subscription_id}/providers/Microsoft.Billing/billingPeriods/{billing_period_name}/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails&api-version=2018-03-31"),  I receive back all records upto but not including the last day.  I was wondering if there were any reasons why it is missing the last date.

Thanks

**Comment by william-inf** [comment]
Any updates on this? @sergey-shandar

**Comment by jackting73** [comment]
Just walked by ... with the same issue this morning and seems found the workaround now.

I'm using PAYG or other non-EA subscription will face the same issue since the API only support EA now ... (got the answer from another thread)

So, I then added some parameters to the request as workaround, the sample request below:

https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Billing/billingPeriods/201808-1/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&**$filter=properties/usageStart ge '2018-05-11' AND properties/usageEnd le '2018-06-12'&api-version=2018-06-30**
