### ISSUE TITLE
[BUG] [chaos@2023-11-01] the `nextLink` property should be null instead of empty string "" when there is no next page

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#31098]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/8ad58020cfafc5ace71d85b31272acf4d6b694d3/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/targetTypes.json#L73

### API Spec version

2023-11-01

### Describe the bug

When calling `TargetTypes_List`, if the result is the last page, the `nextLink` property should be null per the [document](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-pageable) 
![Image](https://github.com/user-attachments/assets/81fb8511-39cc-4c0e-ac05-8990bcbfff62)
However it returned an empty string.
![Image](https://github.com/user-attachments/assets/a46bb69a-aeca-4e81-96e5-ee15b4196ef0)

### Expected behavior

The `nextLink` property should be null when there is no next pages.

### Actual behavior

It returned empty string `""`

### Reproduction Steps

just call `TargetTypes_List`

**Comment by v-jiaodi** [comment]
@MasterRyd3l Please help take a look, thanks.

**Comment by MasterRyd3l** [comment]
this bug is accurately describing the problem. The bug we have is that we are returning a nextLink property with an empty string instead of making it undefined. The nextLinkName property is a schema property aimed at telling autorest codegen which property to use as nextLink. These are completely unrelated. I am closing this bug, as the actual bug is an internal bug tracked on service team's own ADO
