### ISSUE TITLE
Redis returns 500 server error on invalid input for PUT operation on LinkedServers 

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#3158]
**Request:**
`
[main] INFO com.microsoft.azure.management.redis.LinkedServers create - --> PUT https://management.azure.com/subscriptions/000/resourceGroups/javacsmrg06350Second/providers/Microsoft.Cache/Redis/javacsmrc22029Third/linkedServers/javacsmrc22029Third?api-version=2018-03-01
[main] INFO com.microsoft.azure.management.redis.LinkedServers create - 242-byte body:
{"properties":{"linkedRedisCacheId":"/subscriptions/000/resourceGroups/javacsmrg06350Second/providers/Microsoft.Cache/Redis/javacsmrc22029Third","linkedRedisCacheLocation":"Central US","serverRole":"Primary"}}
[main] INFO com.microsoft.azure.management.redis.LinkedServers create - --> END PUT
`
**Response:**
`
[main] INFO com.microsoft.azure.management.redis.LinkedServers create - <-- 500 Internal Server Error https://management.azure.com/subscriptions/000/resourceGroups/javacsmrg06350Second/providers/Microsoft.Cache/Redis/javacsmrc22029Third/linkedServers/javacsmrc22029Third?api-version=2018-03-01 (1391 ms, 36-byte body)
[main] INFO com.microsoft.azure.management.redis.LinkedServers create - 36-byte body:
{"Message":"An error has occurred."}
`

500 indicates retry-able error but in this case input was incorrect. Status code and error message should be revised and fixed.

**Comment by TimLovellSmith** [comment]
Just noticed this. @hovsepm you're saying the input was incorrect because you tried to link the cache to itself? Yes, that should be 400 Bad Request.

**Comment by MECHANDR** [comment]
This issue is fixed now.
**Request:**
`PUT URI: https://management.azure.com/subscriptions/subid/resourceGroups/test/providers/Microsoft.Cache/Redis/geoself/linkedservers/geoself?api-version=2018-03-01
REQUEST BODY: {
	"properties":
	{
		"linkedRedisCacheId":"/subscriptions/subid/resourceGroups/test/providers/Microsoft.Cache/Redis/geoself",
		"linkedRedisCacheLocation":"East US 2",
		"serverRole":"Primary"
	}
}
`
**Response:**
`{
  "readyState": 4,
  "responseText": "{\"error\":{\"code\":\"BadRequest\",\"message\":\"Cannot create redis cache link to itself\\r\\nRequestID=45fd31b3-9dce-4e5c-a5d4-014949e6a126\",\"target\":null}}",
  "responseJSON": {
    "error": {
      "code": "BadRequest",
      "message": "Cannot create redis cache link to itself\r\nRequestID=45fd31b3-9dce-4e5c-a5d4-014949e6a126",
      "target": null
    }
  },
  "status": 400,
  "statusText": "error"
}`
