### ISSUE TITLE
ci seems broken

### ISSUE THREAD

**Issue by pshrosbree** [Azure/azure-rest-api-specs#347]
#345 passes on syntax and node, but fails on python with:

> ERROR:__main__:The msrestazure version 0.4.0 pip package is required to execute the generated code.

Is this a problem in the ci?

**Comment by lmazuel** [comment]
Actually, the error message is:
error: [FATAL] Error saving generated code: Couldn't find the nextLink property specified by extension

The other one is just a bad log. 

This is a mistake in one of the Swagger file and the latest Autorest for Python is more strict than before. Since we download the latest one each time from Travis, the Python build is broken until we fix this file or we skip it in the build. I will skip it at short term to re-enable the build.

**Comment by lmazuel** [comment]
PR merged and CI ok.
