### ISSUE TITLE
resources.subscriptions paging extension error

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#348]
The resources.subscriptions Swagger file has an error

The latest codegen enforce the check for paging extension to make sure there has a property in the response to match the property name specified in extension.

This file presents an error on Travis.

**Comment by xingwu1** [comment]
It looks like the issue has already been addressed.

**Comment by amarzavery** [comment]
[Subscriptions_ListLocations](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/subscriptions/2015-11-01/swagger/subscriptions.json#L65)

**Comment by amarzavery** [comment]
@vivsriaus  
Can you please verify whether Subscriptions_ListLocations is truly pageable? Does it support nextLink? The extension has been defined with nextLink however the model LocationListResult does not have nextLink as a modelProperty. If this is not a pageable operation and you still want (flattening) `IEnumerable\<Location\>` instead of `LocationListResult.value[0] ` to be returned, then please explicitly set nextLink property of the x-ms-pageable extension to null. Check the docs over [here](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-pageable).

**Comment by lmazuel** [comment]
@amarzavery I just can say that I don't have any error with the Python generator.

**Comment by vivsriaus** [comment]
@imazuel I've updated the subscriptions api in the resources spec. Can you please retry your validation?

**Comment by lmazuel** [comment]
All is ok
