### ISSUE TITLE
Consumption API by Billing Period Inaccurate

### ISSUE THREAD

**Issue by louspringer** [Azure/azure-rest-api-specs#3531]
"https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Billing/billingPeriods/{billingPeriodName}/providers/Microsoft.Consumption/usageDetails?api-version=2018-06-30"

The consumption API does not accurately report usage. Although some of the resources have the correct consumption, others are inaccurate, and some resources are missing.

**Comment by louspringer** [comment]
There is a thread at https://docs.microsoft.com/en-us/rest/api/consumption/ describing the same issue. "The data returned by "Consumption Usage Details API" do not add up to the amount shown in the Invoice for the same billing period. For example, the invoice #1001 is $1,000 and uses the billing period 201806-1 but "Usage Details" for that period shows $992. I know both APIs are in preview, but those must MATCH! (if there are not credits)"

**Comment by jackting73** [comment]
+1 Same problem here. However, I got the answer at another thread that this API only support EA subscription now ... not sure whether you are EA subscription or not.

I'm using the API with PAYG subscription then got the same issue with you that the consumed quantity from API didn't match the usage report, then finally I got the root cause that from the usage report. It will remaining some of the usages from previous billing cycle then to be calculated to this billing cycle, however, the API didn't take these usages to be calculated in this billing cycle which from the previous billing cycle.

Not sure this is what you also meet, but I'm still no idea how to solve it ...

**Comment by louspringer** [comment]
There's an older API that appears to return accurate results, see [Get consumption data for an Azure subscription](https://msdn.microsoft.com/en-us/library/azure/mt219001.aspx).

It has some limitations:
* You can't pull usage for a given bill directly. You need to pull usage based on reported usage date.
* Since there is a delay for some resources between when the usage occurs and when it is reported, you must pull usage for a day or so before the beginning of the billing period and then filter it based on the usage date in the data returned by the API.
* The API cannot return more than 1000 records, and it is not paged. This means if you want hourly usage for a month, you need to pull the usage in chunks to ensure you don't attempt to pull more than 1000 usage records. 

I have some crude jupyter notebooks that explore the API and compare the results with the  downloadable CSV file for a given month. I only have one month's data to work with, but for this one month the usage is accurate. See [python-azure-billing-usage](https://github.com/louspringer/python-azure-billing-usage)

**Comment by jackting73** [comment]
Agree with @louspringer ! The older API are accurate mostly but **not** for ALL. 

=Not accurate is the FIRST issue=
From the v1 usage report, there are two parts: the up-side is the total consumed quantity by sub-category this month, and the down-side is the daily consumed quantity. That means by sum of the daily consumed quantity will be equals to the total consumed quantity. However, we found the the response of daily consumed from API is not totally match with the v1 usage daily report, then the monthly consumed will also not match.

- SampleRequest=
https://management.azure.com/subscriptions/{subscription-Id}/providers/Microsoft.Commerce/UsageAggregates?api-version=2015-06-01-preview&reportedStartTime=2018-05-12T00%3a00%3a00%2b00%3a00&reportedEndTime=2018-06-12T00%3a00%3a00%2b00%3a00&aggregationGranularity=Daily&showDetails=false

- Partial Response=
{
"name": "Daily_BRSDT_20180512_0000",
"type": "Microsoft.Commerce/UsageAggregate",
"properties": {
"usageStartTime": "2018-05-11T00:00:00+00:00",
"usageEndTime": "2018-05-12T00:00:00+00:00",
"meterName": "IP Address Hours",
"meterCategory": "Networking",
"meterSubCategory": "Reserved IP",
"unit": "Hours",
"meterId": "26ce34b7-67b3-480d-9d1b-54a7fb80f67a",
"infoFields": {},
"quantity": 6.5999999999999994
}
},
{
"name": "Daily_BRSDT_20180512_0000",
"type": "Microsoft.Commerce/UsageAggregate",
"properties": {
"usageStartTime": "2018-05-11T00:00:00+00:00",
"usageEndTime": "2018-05-12T00:00:00+00:00",
"meterName": "IP Address Hours",
"meterCategory": "Networking",
"meterSubCategory": "Reserved IP",
"unit": "Hours",
"meterId": "26ce34b7-67b3-480d-9d1b-54a7fb80f67a",
"infoFields": {},
"quantity": 5.79999999999999947
}
},
The above response from API show the consumed quantity on 2018-05-11 of Reserved IP was 6.59999 + 5.79999 = **12.399**

- V1

 Usage Report=
The consumed quantity show on usage report on 2018-05-11 is **21.2**
https://vmtestdiag0703.blob.core.windows.net/reservedip/reservedip.PNG

=Can't get the previous(historical) Ratecard is the second issue=
For example, if the price of Basic_A0 VM this month is $20USD and the effectivedate is 2018-08-01, then assume the price last month is $18USD and the effectivedate is 2018-07-01. However, when we use the Ratecard API, we can ONLY get the latest price on 2018-08-01. 
Question here, if we'd like to calculate last month's (2018-07-01) cost, we can only get the latest(2018-08-01) price but without the previous price, how can we calculate the right cost?

**Comment by louspringer** [comment]
@jackting73 for that API you will need to pull a larger window than you want and whittle it down, particularly on the end date. The query is by the date usage is *reported*, but it returns the date of the actual *usage*. 

For the invoice I'm working with, I had to query usage from 6-10-2018 to 7-14-2018 and then parse the results down to the invoice period of 6-12-2018 to 7-10-2018 to get it to match the CSV detail.

The docs for the API do not state how many days after the end of the period usage can come in, but I know it was more then 2 days in my case.  The API doc discusses this issue.

**Comment by jackting73** [comment]
Hi @louspringer , thanks for your help, I realized the reported & actual usage are different.

The most tricky may see here is my billing cycle is from 5-12-2018 to 6-11-2018 on the example above, but the [invoice](https://vmtestdiag0703.blob.core.windows.net/reservedip/reservedip.PNG) will include partial usage on 5-11-2018 which should NOT be in this billing cycle.

So, the paint point here is even pull a larger windows(ex: 5-9-2018 to 6-14-2018) than whittle it down to the right billing cycle (5-12-2018 to 6-11-2018), then sum of the total usage from API never equals to the invoice. (If whittle it down to 5-11-2018 to 6-11-2018, then the total usage will larger than invoice.)

The problem is there **always** will have partial usage from the previous billing cycle then delay to this billing cycle, which the API is not able to calculate accurately.

@jianghaolu , any idea on this ?
