### ISSUE TITLE
authorization paging error

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#354]
The authorization Swagger file has an error

The latest codegen enforce the check for paging extension to make sure there has a property in the response to match the property name specified in extension.

This file presents an error on Travis.

**Comment by amarzavery** [comment]
[ClassicAdministrators_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L64)
[ClassicAdministratorListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L888)

**Comment by amarzavery** [comment]
[PermissionGetResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L919) 

[Permissions_ListForResourceGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L99)

**Comment by amarzavery** [comment]
[ProviderOperationsMetadataListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L1011)

[ProviderOperationsMetadata_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L238)

**Comment by amarzavery** [comment]
[RoleAssignmentListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L1061)

[RoleAssignments_ListForResource](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L310)

**Comment by amarzavery** [comment]
[RoleDefinitions_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L828)
[RoleDefinitionListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-authorization/2015-07-01/swagger/authorization.json#L1151)

**Comment by amarzavery** [comment]
@shuagarw 
Can you please verify whether all the above operations are truly pageable? Do they support nextLink? In all the above methods the pageable extension has been defined with nextLink however the corresponding model  does not have nextLink as a modelProperty. If this is not a pageable operation and you still want (flattening)  IEnumerable\<SomeItem\>  instead of  SomeItemListResult.value[0]  to be returned, then please explicitly set nextLink property of the x-ms-pageable extension to null. Check the docs over [here](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-pageable).

If it supports nextLink then please add nextLink as a property of the corresponding models.

**Comment by lmazuel** [comment]
@amarzavery @shuagarw still broken

**Comment by lmazuel** [comment]
@amarzavery @shuagarw still broken

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/azure-rest-api-specs/pull/542
