### ISSUE TITLE
A typo error in compute.json?

### ISSUE THREAD

**Issue by hellosnow** [Azure/azure-rest-api-specs#3756]
This is transferred from docs feedback: https://github.com/MicrosoftDocs/feedback/issues/635

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall
**Problem:**
Specifies the size of an empty data disk in gigabytes. This element can be used to overwrite the name of the disk in a virtual machine image. 

Should it be overwrite the size of the disk instead of the name of the disk?

Swagger file path: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L5406

cc @celinama

**Comment by lmazuel** [comment]
PR was merged to fix it.

**Comment by hellosnow** [comment]
Thanks! @lmazuel

**Comment by celinama** [comment]
Thanks, I saw this type error got fixed in https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall


**however it still exists in https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines**

diskSizeGB
integer
No
Specifies the size of an empty data disk in gigabytes. This element can be used to **overwrite the name of** the disk in a virtual machine image.
