### ISSUE TITLE
Basic questions around budget API

### ISSUE THREAD

**Issue by murraybutler** [Azure/azure-rest-api-specs#3918]
I had a few questions for the budget API under consumption:

Does the API maintain charge info if I destroy and rebuild the resource group (same name, etc)? 
Is there any way to get granularity to a week (Since I have to use the first of a given month as the start date, am I forced to keep state and do some addition for each week?)?  I have a process that is tearing down resource groups each week.
When the budget is reached, what action occurs on the resource group? Is it shutdown? frozen? Can the user still log in?
I had read that the budget API was in preview in february, but it is in the stable repo as of 6/31. Is the API out of preview?

Sorry for the basic nature of the questions, I'm not sure based upon the doc I can find, what the answers might be.

**Comment by theelderwand** [comment]
@murraybutler please find the responses to your questions,

Does the API maintain charge info if I destroy and rebuild the resource group (same name, etc)?
  - In short, the answer is Yes. Old usage incurred is not removed if your resource group is deleted and is recreated again. Usage data is realized as your Azure resources consume.

Is there any way to get granularity to a week (Since I have to use the first of a given month as the start date, am I forced to keep state and do some addition for each week?)? 
  - This is currently not supported, but something that we can investigate in the upcoming period.

I have a process that is tearing down resource groups each week.
When the budget is reached, what action occurs on the resource group? Is it shutdown? frozen? Can the user still log in?
  - Everything that needs to be done by the budgets when it fires is configured in the budget directly. We support sending an alert e-mail, triggering an action group linked to the budget. You can read more about it here: https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-acm-create-budgets
  - 

I had read that the budget API was in preview in february, but it is in the stable repo as of 6/31. Is the API out of preview?
  - The API is currently out of preview. Please find the documentation here: https://docs.microsoft.com/en-us/rest/api/consumption/budgets

**Comment by kbharucha** [comment]
Closing this issue.
