### ISSUE TITLE
Typo DeletAdd in ADHybridHealthService

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4576]
Should be "DeleteAdd" in the enum values here
https://github.com/Azure/azure-rest-api-specs/blob/bd2aca046b487c2ae2f13cc91d26c5f8aae93571/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L3967

**Comment by amarzavery** [comment]
@gamitra This change was made by you in this PR over [here](https://github.com/Azure/azure-rest-api-specs/commit/4d705b38b39d0f7c163fa98299070c253d8afac4#diff-c2cb03962871ddfd92daee77e1cf44beR3412).

Looks like the enum value should be DeleteAdd and not DeletAdd. Can you please verify what is the actual value expected by the service on the wire? Otherwise it may cause unnecessary errors to our customers using the SDK.

**Comment by nschonni** [comment]
Fixed by #4880
