### ISSUE TITLE
error response of IoT Hub rest API should use camel case

### ISSUE THREAD

**Issue by xscript** [Azure/azure-rest-api-specs#488]
[The definition of ErrorDetails](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-iothub/2016-02-03/swagger/iothub.json#L1400) in IoT Hub rest API should use camel case, instead of Pascal case.
When I use [AutoRest](https://github.com/azure/autorest) to generate the client library (in Azure.Python), error message in below response can't be correctly parsed, because a _message_ property is expected, not _Message_.

``` json
{
  "Code" : "IotHubsQuotaExceeded",
  "HttpStatusCode" : "BadRequest",
  "Message" : "Max number of Iot Hubs exceeded for sku = Free, Max Allowed = 1, Current = 2. If you contact a support representative please include this correlation identifier: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, timestamp: 2016-08-24 05:17:41Z, errorcode: IH400019."
}
```

And there are also other type definition with Pascal case within IoT Hub rest API definition.
Please fix them to use camel case ASAP to avoid further confusion.

**Comment by amarzavery** [comment]
@rmanda - Please take a look at this issue. I have been pointing this out in code reviews. Please make sure that the CSharpiness of the server side implementation does not overflow into the REST API.

**Comment by rkmanda** [comment]
Ack. This will require a fix in the service . Will update here once we push the change out.

**Comment by xscript** [comment]
Hi @rkmanda 
Do you have a timeline for when the fix will be rolled out? We have dependencies on this right now.
We are evaluating whether we should count on your team's fix or work around for short term.
Thanks!

**Comment by amarzavery** [comment]
@lmazuel, @annatisch  - Can you take a look at this issue? It seems like an issue with python sdk.

**Comment by rkmanda** [comment]
Hey @xscript I relooked at this along with @amarzavery and it seems like an issue with the python sdk . Amar will loop in relevant folks to take a look

**Comment by lmazuel** [comment]
Hi,
First, @xscript, I suggest you to use the official build of this SDK in Python: https://pypi.python.org/pypi/azure-mgmt-iothub. Even if we use the same generator, this will give you the right namespace and dependencies. It could be difficult for you to follow which version of Autorest is compatible with which version of msrest/msrestazure runtime. Especially since Python relies on nightly build currently.

Second, we investigated with @annatisch and @rkmanda and the bug is not related to a case problem at all. It's a more subtle problem which needs more internal discussion before suggesting a fix. I will push update here asap.

**Comment by xscript** [comment]
Thanks @lmazuel !
I didn't find the official python SDK for IoT Hub before (back to Aug. 15th). Will give it a try and update here.

**Comment by salameer** [comment]
Hello @xscript I will go ahead and close this task, please re-open again if you're still having this issue after using the official Python SDK.

Thanks
