### ISSUE TITLE
MariaDB GA API Missing Spec

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-rest-api-specs#4894]
The service team [announced](https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-database-for-mariadb/) on December 4, 2018 that they GA'd the MariaDB API. However, I am only able to locate the [MariaDB Preview Spec](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/mariadb/resource-manager) in the azure-rest-api-specs repo.

Can we add the MariaDB GA Specs?

**Comment by ajlam** [comment]
@WodansSon, please use: [Microsoft.DBforMariaDB/stable/2018-06-01](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/mariadb/resource-manager/Microsoft.DBforMariaDB/stable/2018-06-01)

The spec is stable and the API version date was not updated since it was meant to align with the other MySQL and PG specs.
