### ISSUE TITLE
Possible to use swagger-codegen instead of AutoRest?

### ISSUE THREAD

**Issue by dynaxis** [Azure/azure-rest-api-specs#501]
I'm currently exploring the possibility of using Dart client to talk to Azure REST API. Since AutoRest doesn't support Dart, either I have to add support for Dart to AutoRest myself (seems non-trivial) or use swagger-codegen that supports Dart already.
Frankly saying I don't have much experience with Swagger, so curious if it's possible to generate a client using other code generator than AutoRest.

**Comment by dynaxis** [comment]
My question is to know if there is any extension in the Swagger spec in this repo. I'll try myself.

**Comment by brettcannon** [comment]
To my knowledge there are extensions used in the Swagger files.

**Comment by dynaxis** [comment]
@brettcannon my understanding is at least it's possible to generate working client codes ignoring those extensions (I watched a MS video on AutoRest). If not, I have to plug Dart into AutoRest or do manual HTTP requests. BTW, it seems there is no doc describing the architecture of AutoRest yet. Where can I get something useful to reference in case I write generators for Dart?

**Comment by amarzavery** [comment]
@dynaxis - Yes, you would have to process those extensions yourself if you were to write your own generator. We have the logic for polling long running operations hand written in the runtime of every language.

Good news is that we are coming up with a better design of the internal architecture of Autorest.
This will help you serialize the datamodel at different stages. You can then parse the serialized model and plug it in to your code generator. This work will mostly be completed in a sprint.
/cc @fearthecowboy

**Comment by dynaxis** [comment]
@amarzavery could you give me any help if I write a generator for Dart? Where can I start? Just existing ones?

**Comment by amarzavery** [comment]
sure. you can take a look at our exisiting code generators for C#, node.js, java, ruby, etc. All the languages have a generic flavor and an azure flavor ({authentication, paging operations and long running operations} are azure specific).
The generators for all the languages can be found [here](https://github.com/Azure/autorest/tree/master/src/generator). I would recommend taking a look at the C# and node.js lang generators.
Every language generator has a client runtime, that has handwritten code for building the request pipeline, defining the interface and classes for exceptions, etc. This makes it easy to call the runtime methods from the generated code rather than repeating the same stuff in all the operations.

The clientruntime for all the languages can be accessed over [here](https://github.com/Azure/autorest/tree/master/src/client). I would recommend taking a look at the C# or node runtime for starters.

**Comment by AnthShef** [comment]
> Good news is that we are coming up with a better design of the internal architecture of Autorest.
This will help you serialize the datamodel at different stages. You can then parse the serialized model and plug it in to your code generator. This work will mostly be completed in a sprint.
/cc @fearthecowboy

Any updated on the redesign? Any plan to offer a Swift client generator?

**Comment by AnthShef** [comment]
Found OpenAPI Generator (https://github.com/OpenAPITools/openapi-generator), which offers generators in Swift and other languages that I'll ever use.
