### ISSUE TITLE
Naming convention issues with arm-batch swagger spec

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-rest-api-specs#515]
Wrong names are being used in arm-batch swagger specs [https://github.com/Azure/azure-rest-api-specs/blob/b91ba60a90b712d57331762e68829d2666600e4b/arm-batch/2015-12-01/swagger/BatchManagement.json]

Existing Names ->   Should be
SynchronizeAutoStorageKeys   -> SyncAutoStorageKeys [As this is in Rest APIs, or change rest apis]
RegenerateKey ->    RegenerateKeys [As this is in Rest APIs]
Application_AddApplication -> Application_Create
Application_DeleteApplication ->    Application_Delete
Application_GetApplication -> Application_Get
Application_UpdateApplication ->    Application _Update
Subscription_GetSubscriptionQuotas -> Quota_Get
Account -> BatchAccount (as Resource Name is Batch account that should be used in SDK rather than just Account)
Application_AddApplicationPackage -> Version_Create
Application_DeleteApplicationPackage ->Version_Delete
Application_ActivateApplicationPackage ->   Version_Activate
Application_GetApplicationPackage ->    Version_Get
GetApplicationPackageResult & AddApplicationPackageResult ->Both should be Version
AddApplicationParameters -> Application [Should be same as Application resource which we get with applications/{applicationName}/get]
AccountResource & BatchAccountCreateParameters -> BatchAccount [Should be named as per resource type]
/batchAccounts/{accountName}/applications/{id}/versions/{version}/activate -> batchAccounts/{accountName}/applications/{applicationName}/versions/{versionName}/activate -- ID in full resource is which starts from Subscriptions
batchAccounts/{accountName}/applications/{applicationId}    -> batchAccounts/{accountName}/applications/{applicationName}

**Comment by matthchr** [comment]
This issue is quite old and we already went through this exercise with @anudeepsharma.

**Responses inline:**
1. SynchronizeAutoStorageKeys -> SyncAutoStorageKeys [As this is in Rest APIs, or change rest apis] 
  a. We don't feel the need to match exactly the REST API verbiage especially when it is abbreviated**
2. RegenerateKey -> RegenerateKeys [As this is in Rest APIs]
  a. We don't feel the need to match exactly the REST API verbiage especially when it is abbreviated
3. Application_AddApplication -> Application_Create
  a. This is fixed
4. Application_DeleteApplication -> Application_Delete
  a. This is fixed
5. Application_GetApplication -> Application_Get
  a. This is fixed
6. Application_UpdateApplication -> Application _Update
  a. This is fixed
7. Subscription_GetSubscriptionQuotas -> Quota_Get
  a. This was changed to Location_GetQuotas
8. Account -> BatchAccount (as Resource Name is Batch account that should be used in SDK rather than just Account)
  a. This is fixed.
9. Application_AddApplicationPackage -> Version_Create
  a. This is now called ApplicationPackage_Create
10. Application_DeleteApplicationPackage ->Version_Delete
  a. This is now ApplicationPackage_Delete
11. Application_ActivateApplicationPackage -> Version_Activate
  a. This is now ApplicationPackage_Activate
12. Application_GetApplicationPackage -> Version_Get
  a. This is now ApplicationPackage_Get
13. GetApplicationPackageResult & AddApplicationPackageResult ->Both should be Version
  a. Response is now ApplicationPackage
14. AddApplicationParameters -> Application [Should be same as Application resource which we get with applications/{applicationName}/get]
  a. Not fixed, because the way the C# code generator would generate this is confusing (all properties would be settable via the constructor which implies get-only properties might be transited to the server)
15. AccountResource & BatchAccountCreateParameters -> BatchAccount [Should be named as per resource type]
  a. AccountResource was changed to BatchAccount. BatchAccountCreateParameters was left as is for the same reasoning as 14 above.
16. /batchAccounts/{accountName}/applications/{id}/versions/{version}/activate -> batchAccounts/{accountName}/applications/{applicationName}/versions/{versionName}/activate -- ID in full resource is which starts from Subscriptions
  a. Changed `id` to `applicationId` to clarify.
17. batchAccounts/{accountName}/applications/{applicationId} -> batchAccounts/{accountName}/applications/{applicationName}
  a. Discussed and didn't change this because `applicationId` is not `id`

**Comment by matthchr** [comment]
@kirthik I think we can close this, as all of the issues were discussed and either resolved or deferred.
