### ISSUE TITLE
Inconsistencies in PublicIPAddress in Network.json

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-rest-api-specs#554]
Hi there,

This spec references an object for PublicIPAddress:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-06-01/swagger/network.json#L6959

However there are two places in the spec where the object is not referenced:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-06-01/swagger/network.json#L4491

And:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-06-01/swagger/network.json#L7552

Every other mention of this field in the spec has the correct reference:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-06-01/swagger/network.json#L7552

Is this intentional? This is currently causing some deserialization errors in the Python SDK.
https://github.com/Azure/azure-sdk-for-python/issues/786

If this is in fact the intended behaviour we will need to make modifications to the Python generator to accommodate it.
The Python SDK is currently generated from the 2016-06-01 spec, but this issue also seems to appear if the 2016-09-01 spec.

Thanks,
Anna

**Comment by annatisch** [comment]
@amarzavery - do you know who the best person would be to contact regarding this issue in the network spec?

**Comment by amarzavery** [comment]
So the spec is correct. The issue described above is not an issue in C# or node.js sdk.
The PublicIpAddress is a sub resource a.k.a reference to the publicIP. The user can get more information about it by doing a GET on the id provided for public IP. 
If the entire object is provided over there then the encompassing object (VirtualNetworkGatewayIPConfiguration) becomes lengthy.

Usually the GET operation for the resource type that one is creating has a $expand query parameter. If you provide the values that you want to expand on, (Public IP in this case) then the service should provide you the complete object rather than the reference.

**Comment by annatisch** [comment]
Thanks @amarzavery - I'll take another look!

**Comment by liumichelle** [comment]
@DeepakRajendranMsft to close this issue

**Comment by salameer** [comment]
Hi @liumichelle,

Can you please add more description on why this is  to be resolved?

**Comment by liumichelle** [comment]
I believe @amarzavery was able to answer the question if you check the thread above.

**Comment by liumichelle** [comment]
@salameer can this issue be closed out?

**Comment by liumichelle** [comment]
@salameer - can this issue be closed out I believe @amarzavery answered the question.

**Comment by salameer** [comment]
Closing
