### ISSUE TITLE
UnDocumented API Version for Cosmos DB

### ISSUE THREAD

**Issue by wilsonge** [Azure/azure-rest-api-specs#5968]
The only API listed under CosmosDB is the one listed here: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB 

However here https://docs.microsoft.com/azure/cosmos-db/manage-sql-with-resource-manager there is a clear implications that there is a 2016-03-31 release. This was further added here https://github.com/MicrosoftDocs/azure-docs/issues/30853

Can we please have this missing api version added!

**Comment by MehaKaushik** [comment]
Thanks for bringing this up. I will get back to you with a tentative timeline.

**Comment by MehaKaushik** [comment]
Hi @wilsonge @karok2m since these are old APIVersions, the documentation would not be affected, neither new SDKs would be released for them. Our future APIVersions support and enhance the features in these APIVersions. Our recommended APIVersions is 2020-04-01. We would not invest in maintaining older versions + there are additional internal reasons, hence we would not document these apiVersions.

**Comment by MehaKaushik** [comment]
Please feel free to re-open this if you have any other concerns.
