### ISSUE TITLE
Filter `substringof` and `top` parameter cannot work together in Resources#List

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#6967]
When I call rest api
```
/subscriptions/${subscriptionId}/resources?$top={top}&api-version=2018-05-01&$filter={filter}
```
and filter contains a clause of `substringof`, then the `top` parameter will be ignored.

To reproduce:

I used Postman to send this rest api request. Armclient or az CLI cannot get the filter in this request to work. I filed another [issue](https://github.com/projectkudu/ARMClient/issues/51) about this in the armclient repo.

Use postman and call GET
```
https://management.azure.com/subscriptions/${subscriptionId}/resources?$top=2&api-version=2018-05-01&$filter=substringof('test', name)
```

**Expected behaviour**: Getting a response with 2 entries with name contains `test` in them and a `nextLink` for a url that I can fetch rest part of the full result list.

**Actual behaviour**: Getting a full list of filtered resources, as if the top parameter get ignored.

If I replace this filter with another one without `substringof` clause, the top parameter works fine.

**Comment by snaheth** [comment]
@ArcturusZhang - Not sure how no one looked at this yet but here I am 😄 I see that this issue still exists even in the new api-version so I'll add this to our backlog to address.

**Comment by DeloitteAnwarBashaP** [comment]
@ms
Any update for this issue?

**Comment by tim-nguyen-cs** [comment]
Hi @DeloitteAnwarBashaP , while investigating this issue previously, we ran into a conflict with how resources are queried, which prevented the proper number of resources from being returned. Because this is a design constraint, the observation is to be expected, and the relevant documentation for this API has been updated with the following note: `Note that any truncated number of results queried via $top may also not be compatible when using a filter.`
