### ISSUE TITLE
Duplicated operationid break Rest Document CI

### ISSUE THREAD

**Issue by yishengjin1413** [Azure/azure-rest-api-specs#7048]
These two files:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azsadmin/resource-manager/network/Microsoft.Network.Admin/preview/2015-06-15/Network.json

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/Location.json

Both contains operationid: `Locations_List` which break the Rest Document CI and make the content not updated with the new change in this repo: https://github.com/Azure/azure-docs-rest-apis . 

Would anyone help to rename one operationId?

**Comment by weidongxu-microsoft** [comment]
@zhiyuanxia Could you rename your operationId since yours are newly added API? Or I will have to revert the merge or PR 6933.

@rloutlaw I will try to revert that merge within a few hours if the fix does not come in time. Sorry for the problem (it is hard to tell on PR along since they are in 2 different services, and validation tool does not find them).

**Comment by zhiyuanxia** [comment]
I will change the name right now.

**Comment by zhiyuanxia** [comment]
Hi Weidong,

I have created a new PR with my changes and a new operation ID for locations.

https://github.com/Azure/azure-rest-api-specs/pull/7053

Please let me know if there is anything else I can do.

Thanks,
Michael

**Comment by weidongxu-microsoft** [comment]
@rloutlaw The duplicated operationId is solved via https://github.com/Azure/azure-rest-api-specs/pull/7053, and merged.
