### ISSUE TITLE
Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#711]
When trying to create a deployment with the following `resource_group_name` **colemick-k8s-kube15-test000** the following error is returned:

`Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.`

The offending line is: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-09-01/swagger/resources.json#L140

This regex is used throughout; however, this name does match the regex `^[-\w\\._\\(\\)]+$`.  Is there something wrong with the resource group name or the regex?

**Comment by tjprescott** [comment]
cc/ @colemickens

**Comment by TianoMS** [comment]
@tjprescott The resource group name "colemick-k8s-kubie15-test000" is valid. The regex is correct too. How did you repro the  issue?

**Comment by lmazuel** [comment]
@TianoMS @tjprescott 
Actually, the correct regexp is `^[-\w\._\(\)]+$` (dev language agnostic). 
![image](https://cloud.githubusercontent.com/assets/1050156/23031583/5efd3fe8-f426-11e6-9233-8247065b5b63.png)

And JSON does not require any escaping here (IOW, no double escape is necessary to write this string in a JSON file).
If some language needs a double escaping for some reason, it should be the work of the generator for this language to do it in Autorest.
I guess it's too late now, because it will break a lot of people. At least we need to be consistent, so if we need to de-escape in Python we do it the same way each time.

**Comment by lmazuel** [comment]
@TianoMS @tjprescott 
My mistake, yes the correct regexp is `^[-\w\._\(\)]+$`, but JSON **does** require escaping of `\`, so it has to be written in the JSON file:
`^[-\\w\\._\\(\\)]+$`

So sorry @tjprescott , seems to me too it's correct in the Swagger :(

**Comment by lmazuel** [comment]
@tjprescott your regexp is correctly unescaped in Python:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/operations/deployments_operations.py#L217

And:
![image](https://cloud.githubusercontent.com/assets/1050156/23032309/c932b0a8-f428-11e6-9f78-7b9f2d118ff2.png)

I don't deny your issue, maybe we should look in the Python side and close this issue?

**Comment by kirthik** [comment]
@lmazuel : Did you get a chance to investigate this issue from Python side? Can we close this one?

**Comment by lmazuel** [comment]
@kirthik I still think there is no issue in the Swagger file and we can close this issue, but it's the call of @tjprescott

**Comment by ravbhatnagar** [comment]
Looks like this is not an issue. @tjprescott - please let us know if you feel otherwise and we can take a look again.

**Comment by ravbhatnagar** [comment]
@kirthik  - please close the issue.
