### ISSUE TITLE
App Service Plans Missing Number of Workers

### ISSUE THREAD

**Issue by mattsp1290** [Azure/azure-rest-api-specs#7990]
The current model for app service plans is missing number of workers. When I go to https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/list and try it, in the properties sent back, I have number of workers available. But this value is not in the sample response nor the definition of a Service Plan https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/list#appserviceplan As such this has not made it over to the Python SDK.

**Comment by mattsp1290** [comment]
Here is an example of one of the service plans I get back from the API above with some info redacted
```javascript
{
    "id": "<resource_id>",
    "name": "<name>",
    "type": "Microsoft.Web/serverfarms",
    "kind": "linux",
    "location": "Central US",
    "properties": {
        "serverFarmId": <server_farm_id>,
        "name": "<name>",
        "workerSize": "D1",
        "workerSizeId": 3,
        "workerTierName": null,
        "numberOfWorkers": 2,
        "currentWorkerSize": null,
        "currentWorkerSizeId": null,
        "currentNumberOfWorkers": null,
        "status": "Ready",
        "webSpace": "<web_space>",
        "subscription": null,
        "adminSiteName": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "maximumNumberOfWorkers": 30,
        "planName": "<plan_name>",
        "adminRuntimeSiteName": null,
        "computeMode": "Shared",
        "siteMode": null,
        "geoRegion": "Central US",
        "perSiteScaling": null,
        "maximumElasticWorkerCount": null,
        "numberOfSites": 0,
        "hostingEnvironmentId": null,
        "isSpot": null,
        "spotExpirationTime": null,
        "freeOfferExpirationTime": null,
        "tags": null,
        "kind": "linux",
        "resourceGroup": "<resource_group>",
        "reserved": null,
        "isXenon": null,
        "hyperV": null,
        "mdmId": null,
        "targetWorkerCount": null,
        "targetWorkerSizeId": null,
        "provisioningState": null,
        "webSiteId": null,
        "existingServerFarmIds": null
    },
    "sku": {
        "name": "P1v2",
        "tier": "PremiumV2",
        "size": "P1v2",
        "family": "Pv2",
        "capacity": 2
    }
}
```

**Comment by lilyjma** [comment]
@antcp, @AzureAppServiceCLI, can you please take a look?

**Comment by craigeebach** [comment]
This issue seems to have been dropped, but it's still a problem.  App Service Plans have a configurable `numberOfWorkers` property.  For example we can change this property in the azure portal UI in the "Scale Out" section:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/20073455/170698425-16c44348-009f-4387-9f74-5013ea4a5437.png">

This scale action corresponds to the `numberOfWorkers` property of the app service plan as shown in the json view of the app service plan:
![image](https://user-images.githubusercontent.com/20073455/170691596-4309fac0-4fa2-4034-a708-9e62d9661ba8.png)

And is available from the REST API that lists app service plans: 
![image](https://user-images.githubusercontent.com/20073455/170698866-4fe2f73f-a35d-4d44-a60e-dbbb01933f65.png)

Does PR https://github.com/Azure/azure-rest-api-specs/pull/19254 help get this issue reassigned and fixed?

**Comment by craigeebach** [comment]
FYi @weidongxu-microsoft this is the issue on the azure-rest-api-specs side.  Anything can be done to resolve this somehow?  Thanks.

**Comment by weidongxu-microsoft** [comment]
Let's see if CXP can help.

**Comment by navba-MSFT** [comment]
@weidongxu-microsoft We are removing the CXP attention label from this, Since Service team has already been involved. Also RESTAPI specs repo was onboarded to CXP in April 2022. However, this issue is open since 2019. This will be considered as backlog and CXP can help only on best effort basis.

@antcp @AzureAppServiceCLI Could you please look into this issue on priority and provide an update on this ? Awaiting your reply.

**Comment by mattsp1290** [comment]
Appears to have been addressed in https://github.com/Azure/azure-sdk-for-java/pull/29110 and the communication did not cross over.
