### ISSUE TITLE
Azure Container Service: Clarification for the Service Principal

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#836]
:wave: ¡hola!

To start off with a smile - you [may remember me](https://www.youtube.com/watch?v=AtIpdvPDXQU) from some of the other issues I filed this afternoon 🙈

![inline](https://upload.wikimedia.org/wikipedia/en/6/6c/Troymcclure.png)

So.. I've added [support for DCOS, Kubernetes and Swarm to Terraform which works like a charm](https://github.com/hashicorp/terraform/pull/10820) - however there's some undocumented behaviour I'm seeking some clarification on:

When provisioning a Container Service instance - with the `Orchestration Platform` set to `Kubernetes` - the field `ServicePrincipal` is required. However when the `Orchestration Platform` is set to `DCOS` or `Swarm` it's a validation failure.

My questions/comments/thoughts are:
 - Why is this only required for the Kubernetes Orchestration Platform, rather than all of them?
    - Given they're all in the same API call - as it is it's really hard to add validation.
    - If each provider is fundamentally different - shouldn't they each have their own API - or at least their own types? If not - shouldn't this be required across all of them? Presumably this is used for auto-scaling the agents?
 - Is it not possible to infer this information providing via the API? Clearly as a Consumer we could provide this as a default - but it's not ideal
 - Whatever the behaviour - shouldn't it be documented?

I think this is the most relevant place to file this - but feel free to tell me if I need to file this somewhere else :)

Thanks!

**Comment by colemickens** [comment]
cc: @Azure/acs 

>Why is this only required for the Kubernetes Orchestration Platform, rather than all of them?

Because only Kubernetes has tight integration built-in for talking to Azure APIs to do things like routing rules or creating load balancers.

As for the follow-up questions here, I'll have to let someone else speak to them. At this point though, I don't think we're in a position to make very extensive changes to the API surface (though it *is* versioned).

>Is it not possible to infer this information providing via the API? Clearly as a Consumer we could provide this as a default - but it's not ideal

Not sure I understand the question here. If you're asking if ACS could automatically determine a ServicePrincipal, the answer is no, not really. If you're asking if ACS could mint a ServicePrincipal automatically, the answer is maybe, but we decided not to do that for now. 

>Whatever the behaviour - shouldn't it be documented?

Yes. We should tag in @squillace and @rgardler / @sauryadas for assistance in this area.

**Comment by tombuildsstuff** [comment]
Thanks for the fast reply @colemickens - apologies for the number of issues opened - seemed like a better way to handle them :)

> > Is it not possible to infer this information providing via the API? Clearly as a Consumer we could provide this as a default - but it's not ideal
> 
> Not sure I understand the question here. If you're asking if ACS could automatically determine a ServicePrincipal, the answer is no, not really. If you're asking if ACS could mint a ServicePrincipal automatically, the answer is maybe, but we decided not to do that for now.

I'm not sure, but I have a feeling "mint" may be the auto-correct for mount?

Possibly - I was more wondering why it's needed at all - surely if Azure's has permissions to monitor this, there's could be permissions to handle the scaling/associated resources via the same token, without needing to specify one here explicitly?

As a consumer of the API (i.e. calling the SDK) - we could pass in the Service Principal details being used  - however this is likely to have a higher access rights than something scoped for the associated Container Service resources.

**Comment by colemickens** [comment]
>Thanks for the fast reply @colemickens - apologies for the number of issues opened - seemed like a better way to handle them :)

No worries, I strongly prefer separate issues anyway.

>I'm not sure, but I have a feeling "mint" may be the auto-correct for mount?

"mint" == "create" here. ACS could create the SP automatically on behalf of the user, but we chose not to do this for now.

>Possibly - I was more wondering why it's needed at all - surely if Azure's has permissions to monitor this, there's could be permissions to handle the scaling/associated resources via the same token, without needing to specify one here explicitly?

Not sure I understand the question/statement here. High level: Kubernetes calls into Azure ARM endpoints to create Routes in RouteTables, create LoadBalancers and LoadBalancer rules. For Kubernetes to talk to ARM, we need to have credentials, hence the ServicePrincipal. Note, this has to be manually specified because Azure doesn't not currently have a capable metadata/token endpoint like GCE/AWS have.

>As a consumer of the API (i.e. calling the SDK) - we could pass in the Service Principal details being used - however this is likely to have a higher access rights than something scoped for the associated Container Service resources.

Correct, I ran into this exact same problem with `kubernetes-anywhere` with Terraform. Resource groups are great, but it gets to be a thorny spot... Imagine you don't have the resource group created yet, you can't actually create the resource group unless the SP has Write access on the Subscription itself, which is undesirable. And as you point out, there's no reason for the SP used by Kubernetes to have full access to the Subscription. A bit of a chicken/egg problem.

Unfortunately, I don't have a great suggestion for how to handle the latter case. One option would be to have the user create the SP ahead of time, create a Terraform resource for an RBAC assignment and then implicitly create an RBAC assignment for the extra-user-supplied SP behind the scenes. This is something I'm toying with (in ARM templates) as I brainstorm and prototype ways out of this manual SP management business entirely.

**Comment by brendandburns** [comment]
This issue should probably be closed, there's nothing we can really do here, unless we want to leave this open until we add SP creation to the ACS API.
