### ISSUE TITLE
[CompositeSwagger] Versioning of composite swaggers

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#840]
Today, composite Swagger JSON files are not versioned. Consider we have a service `Foo` as following:
```
arm-foo
|- compositeFooClient.json
|--- 2016-02-29 leapyear.json
|--- 2016-12-25 christmas.json
```
as we are generating SDK 1.2.3 from that. Customers are happy with it.

2 months later, arm-foo released new api versions:
```
arm-foo
|- compositeFooClient.json
|--- 2017-02-28 normalyear.json
|--- 2017-02-28 christmas.json
```
and we release 2.0 version of the SDK.

3 days later, customer using 1.2.3 found a bug that needs a fix, AFAIK there's no way to partially generate code off `leapyear.json` under api version `2016-02-29`. 

### Proposal
Put composite swagger JSONs into versioned folders. This version can also be the semantic version of the service, which can be kept consistent across different languages.

**Comment by lmazuel** [comment]
I agree that we need something to better version Composite file. However "semantic version of the service" is something to be define very carefully. I really think it's not possible to keep a equivalent version number between packages in difference language, since Autorest bugs can be only for one language sometimes (for instance, I moved from IotHub Python 0.2.0 to 0.2.1 because of an Autorest bug that was only in Python). Bug fixes can be breaking and force to change the major version number (already seen that). Also, some Swagger changes are not breaking for a language (changing Enum "model as string" is not breaking in Python, but will be in C#)

So, ok for "semantic version of the service", but this will not be the package unique version for every language.

My two cents,

**Comment by kirthik** [comment]
@jianghaolu - Would you please present this proposal in the biweekly discussion meeting?

**Comment by jianghaolu** [comment]
I don't have a crispy clear idea of what it should look like but yeah we can discuss about this tomorrow.

**Comment by jianghaolu** [comment]
@kirthik ah I mean next Thursday.

**Comment by salameer** [comment]
Closing this since we seem to have moved on to a totally different model
