### ISSUE TITLE
Azure Container Registry: Documentation / SDK mismatch

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#842]
:wave: hello!

I've been checking the [Documentation for Azure Container Registry](https://docs.microsoft.com/en-us/rest/api/containerregistry/registries#Registries_CreateOrUpdate) which states that the CreateOrUpdate call can return an HTTP 202 in addition to a HTTP 200. However at the moment the SDK only expects a HTTP 200.

In all of the testing that I've done with this, I've not yet seen a HTTP 202 (which means I'm unable to confirm the behaviour either way) - but it leads me to think that the Documentation is wrong here?

Would it possible to clarify what the expected behaviour is please? :)

Thanks!

**Comment by mcardosos** [comment]
@djyou

**Comment by djyou** [comment]
The CreateOrUpdate/PUT call was designed to support asynchronous resource creation but right now it is only implemented as a synchronous operation. Therefore, at least for the current preview api-version, you can expect that 202 will not be returned from CreateOrUpdate/PUT calls.

The SDK was generated from swagger spec directly in which 202 is considered as a successful response. Currently there is no polling logic in the SDK besides treating 202 as a successful response in the same way as 200. In fact, if you are an SDK user, 200/202 shouldn't make a difference because the SDK will take care of polling status (if 202 is ever returned) and eventually return 200 if resource creation is successful.

/cc @SajayAntony
