### ISSUE TITLE
Any reference to the Azure Portal and how it handles the calls?

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-rest-api-specs#8678]
I'm trying to reconsile the way the Azure Portal handles some info and some operations in comparison to a more programmatically way, for example, in Powershell.
I can't find any information regarding the Portal.
For example, some Virtual Machines, in the Portal, have a 
`Operating system: Windows Server Datacenter 2016`
property
But the information is completely blank when accessing the API using the reference.
For example, for the same VM, consulting [this reference ](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)
and using, for example, "storageProfile" property comes out blank....

Same thing happens when trying to understand the way a VM references the Recovery Service Vault in the Portal, from the Dashboard.
I can't find any way of handling that request programmatically, but in the Portal it's only one click.
Any ideas?

**Comment by MyronFanQiu** [comment]
I'm sorry. I think we don't have such documentation. We do have some documentation which should help.
https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-3.6.1
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-powershell

**Comment by Drewm3** [comment]
@DanteNahuel, there are 3 possible places in the APIs which may return the operating system running on the VM. The various locations have slightly different context and reliability. Let me list these here, and I can provide more details on specific APIs for the area in which you are interested:

1.) VMs deployed from a platform image will contain the image details which may indicate the OS version in the publisher selected names for Offer or SKU. However, these are publisher selected so there is no guarantee the OS will be discoverable in the naming. (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get) 

2.) Each OS Disk will have a specified value of Windows or Linux. This value is inherited from the image when the OS Disk was created from an image. When an OS disk is uploaded to the platform directly, then the OS value is set when the OS disk is created. This value is always present, but the Azure platform does not ensure it is correct. So you may or may not want to take a dependency on this. (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)

3.) Running VMs that include the guest agent (All Linux VMs and most Windows VMs) will show the OS Name and OS Version in the VM Instances view. This is accurate at all times, but due to the fact that the information comes from the guest agent it will not be available for all VMs. (API: (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get using the Instance View parameter)

Please let me know if this answers your question, or if additional details are neede.

**Comment by DanteNahuel** [comment]
> @DanteNahuel, there are 3 possible places in the APIs which may return the operating system running on the VM. The various locations have slightly different context and reliability. Let me list these here, and I can provide more details on specific APIs for the area in which you are interested:
> 
> 1.) VMs deployed from a platform image will contain the image details which may indicate the OS version in the publisher selected names for Offer or SKU. However, these are publisher selected so there is no guarantee the OS will be discoverable in the naming. (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)
> 
> 2.) Each OS Disk will have a specified value of Windows or Linux. This value is inherited from the image when the OS Disk was created from an image. When an OS disk is uploaded to the platform directly, then the OS value is set when the OS disk is created. This value is always present, but the Azure platform does not ensure it is correct. So you may or may not want to take a dependency on this. (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)
> 
> 3.) Running VMs that include the guest agent (All Linux VMs and most Windows VMs) will show the OS Name and OS Version in the VM Instances view. This is accurate at all times, but due to the fact that the information comes from the guest agent it will not be available for all VMs. (API: (API: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get using the Instance View parameter)
> 
> Please let me know if this answers your question, or if additional details are neede.

This does answer my question in a practical way. I understand it now.
However, my concern is that this information is not clear in the Documents.

**Comment by Drewm3** [comment]
Thanks for the feedback. Let me have someone look through the docs to see if we can clarify everything in the API documentation.

**Comment by Vaibhav-Agar** [comment]
@DanteNahuel, Just providing an update that we are in the process of updating the documentation to provide more clarity. The doc changes should be published soon.

**Comment by Vaibhav-Agar** [comment]
This was added as an FAQ in documentation [here ](https://docs.microsoft.com/azure/virtual-machines/windows/vm-usage). Closing.
