### ISSUE TITLE
[Azure Monitor] Incorrect definition of Channels (should be Array)

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#890]
Using ActivityLog (Events), the object is EventData. This contains a "channels" attribute:
```json
       "channels": {
          "type": "string",
          "description": "the event channels. The regular event logs, that you see in the Azure Management Portals, flow through the 'Operation' channel.",
          "enum": [
            "Admin",
            "Operation",
            "Debug",
            "Analytics"
          ],
          "x-ms-enum": {
            "name": "EventChannels",
            "modelAsString": false
          }
        },
```

But this attribute might contain in the real RestAPI this string:
```json
"channels":"Admin, Operation"
```
That is not one the value in the Enum, but an array of the available value in the enum. This fails the deserialization in the client.

Root cause of: https://github.com/Azure/azure-sdk-for-python/issues/969

FYI @vishrutshah

**Comment by gucalder** [comment]
Definitely an issue.
I'll work on a fix for this one.

**Comment by lmazuel** [comment]
@gucalder I was thinking about this, I don't think we can consider "Admin, Operation" as an array (it's not an array in the JSON). We cannot do real better than `string` it seems. Either a real `string`, or change `modelAsString` as True to still keep an "enum-like" parameter (in Python, `modelAsString` to True just authorized a multi-type parameter String or Enum, so it's more accurate than a pure `string` type)

@olydis @amarzavery for guidance

**Comment by vishrutshah** [comment]
@gucalder Do we have an ETA on the fix? We'd like this to be fixed so that can have python cli command line experience to be released in preview for Azure Monior services.

**Comment by gucalder** [comment]
Yeap, the server responds with a string. It is a Flags Enum serialized as a csv-string.
Talking to people here, they say that we can just take that channels field out of the spec since it really has no meaning now. We are using categories instead of channels.

Since we are going to rename everything, then I will make all the changes now in the new package.
We will take the pain since everything will need changes to work again (our SDK, PowerShell, Node.js), but you guys will be unblocked. I am going to change replace insights with monitoring in the file names, package names, etc.
My team is reviewing the code now. I'll send the PR soon tomorrow morning.

**Comment by gucalder** [comment]
This is resolved now with the new Monitor folder.
I removed the Channels from the spec since it currently has no meaning. With time it became irrelevant for us.

**Comment by johnkemnetz** [comment]
@kirthik can you close this since it is now resolved?
