### ISSUE TITLE
PatternAnalyzer.pattern incorrectly states the default is whitespace

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9145]
The documentation for Azure Search for PatternAnalyzer.pattern incorrectly states that the default is whitespace, as well as saying that it matches token separators when, in fact, it appears to match token words. It seems as if it was copied and pasted from PatternTokenizer.

Part of Azure/azure-sdk-for-net#11457

**Comment by brjohnstmsft** [comment]
@heaths `PatternAnalyzer` and `PatternTokenizer` both match token separators, and the default for both is `\W+`, which matches all non-word characters. I'm updating the descriptions to say "non-word" instead of whitespace. I'm also updating our REST API docs with the same change, as well as fixing a typo where we incorrectly state the default for `PatternAnalyzer` to be `\w+` when it should be `\W+`.
