### ISSUE TITLE
[Time Series Insights] Fix inconsistency between API spec and actual service

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-rest-api-specs#9194]
Fix inconsistency between API spec and actual service. Details can be found at 
[TimeSeriesInsights Speclet.docx​​​​​​​](https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EeASGSS9OH5EoETiy56ZqKYBr85-KD5u6uxLJt3QIVNg8A?e=7Nw2tV).

**Comment by riserrad** [comment]
Hi @jiasli , could you please enumerate the remaining issues we still need to look into?

As far as I'm aware, the majority of the blocking issues were already taken care on the PR below:

https://github.com/Azure/azure-rest-api-specs/pull/8758

There are two remaining items that are going to be fixed in our backend but they don't seem to be blockers.

It would be great if we could have a GitHub issue per issue on your doc for better tracking.

**Comment by riserrad** [comment]
> Hi @jiasli , could you please enumerate the remaining issues we still need to look into?
> 
> As far as I'm aware, the majority of the blocking issues were already taken care on the PR below:
> 
> #8758
> 
> There are two remaining items that are going to be fixed in our backend but they don't seem to be blockers.
> 
> It would be great if we could have a GitHub issue per issue on your doc for better tracking.

Hi @jiasli - following up with you on this issue. Do we still have issues from your point of view? If so, can you please enumerate them?

**Comment by k-rush** [comment]
Hi @jiasli , can you please help us determine what issues still exist for us? The action we need to take is not clear to me from looking at the provided doc.

cc @riserrad

**Comment by k-rush** [comment]
Closing for now, @jiasli please re-open if there are any more actionable steps for us to take.
