### ISSUE TITLE
Tags aren't added to resources Backup Policy and Backup Protected

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#9251]
Symptom:
Tags aren't added to resources Backup Policy resource and it exists same problem on Backup Protected resource.

RP:
RecoveryServicesBackup

Rest api call for Backup Policy:
```
PUT https://management.azure.com/Subscriptions/xx-xxx-xx-xxx/resourceGroups/acctestRG-backup-200428101859805137/providers/Microsoft.RecoveryServices/vaults/acctest-200428101859805137/backupPolicies/acctest-200428101859805137

{
	"properties": {
		"backupManagementType": "AzureIaasVM",
		"retentionPolicy": {
			"dailySchedule": {
				"retentionTimes": [
					"2018-07-30T23:00:00Z"
				],
				"retentionDuration": {
					"count": 10,
					"durationType": "Days"
				}
			},
			"retentionPolicyType": "LongTermRetentionPolicy"
		},
		"schedulePolicy": {
			"schedulePolicyType": "SimpleSchedulePolicy",
			"scheduleRunDays": [],
			"scheduleRunFrequency": "Daily",
			"scheduleRunTimes": [
				"2018-07-30T23:00:00Z"
			]
		},
		"timeZone": "UTC"
	},
	"tags": {
		"env": "Test"
	}
}
```

Response:
![image](https://user-images.githubusercontent.com/19754191/80441296-36958380-893d-11ea-9c9c-34bc3f5666c1.png)

**Comment by neil-yechenwei** [comment]
Hi @pratimaupadhyay02 , I found some changes from you for this API (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2019-05-13/bms.json). Could you help to have a look this issue? Thanks.

**Comment by pvrk** [comment]
@neil-yechenwei : We don't have a way to save/retrieve tags on backup resources today. Then it might be consistent to remove them from the request body/definition so that this impression is not given. Let me check with my engg team regarding the removal of this tags and come back to you.

**Comment by pvrk** [comment]
@neil-yechenwei : We got a response from ARM team. Tags for Azure Proxy resources such as these are not supported by ARM yet. What would be ideal solution from your end? Can you ignore them for now or do we have to explicitly remove them from our request/response?

**Comment by pvrk** [comment]
@neil-yechenwei :  Another gentle reminder

**Comment by neil-yechenwei** [comment]
@pvrk , thanks for your response. Could you help to explicitly remove them from your request/response since it's not useful? Does it make sense?

**Comment by tombuildsstuff** [comment]
@pvrk is there a timeline for fixing the API to support this?

Since we've already shipped support for tags on this resource (and [users are filing issues about it not working](https://github.com/terraform-providers/terraform-provider-azurerm/issues/5729)) we're unable to remove these tags outside of a major version since this'd be a breaking change (and as such I'm going to close https://github.com/terraform-providers/terraform-provider-azurerm/pull/7127 which proposes removing them)

**Comment by pvrk** [comment]
@tombuildsstuff : This is a general question for ARM team. Whenever they start supporting tags for proxy resources, then we can plan to leverage that.

**Comment by pvrk** [comment]
Closing this issue since this is related to ARM and not to Azure Backup alone.

**Comment by tombuildsstuff** [comment]
@pvrk since this is tracking this bug in the Backup API's - shouldn't this stay open until either the ARM Platform provides a manner to configure these and/or the API is updated to manage those itself?ixed

**Comment by pvrk** [comment]
@tombuildsstuff : We are being tracked on the response of every bug. For feature requests, there may not be any updates for quite some time. And this is not a feature request on our team too and hence I don't know when ARM team will prioritize this request. So, IMO, it is better to open a generic issue on ARM team about supporting tags for proxy resources and track it against them. When they do it, then we can leverage that and give the relevant functionality.

Another option is to re-open this bug and tag it against the ARM team (instead of recovery services team).

Please let me know your preferred option.
