### ISSUE TITLE
Create resource error by following the swagger and examples

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9462]
When I try to create privateCloulds by using the example https://github.com/Azure/azure-rest-api-specs/blob/master/specification/vmwarevirtustream/resource-manager/Microsoft.VMwareVirtustream/preview/2019-08-09-preview/examples/PrivateClouds_CreateOrUpdate.json, I get the 400 bad request with error message:
```
{
    "error": {
        "code": "DisallowedResourceOperation",
        "message": "The operation 'write' on resource type 'privateClouds' is disallowed."
    }
}
```
The request I used is:
```
curl --location --request PUT 'https://management.azure.com/subscriptions/7fd08dcc-a653-4b0f-8f8c-4dac889fdda4/resourceGroups/weidongtest/providers/Microsoft.VMwareVirtustream/privateClouds/dwtest?api-version=2019-08-09-preview' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw ' {
  "location": "eastus2",
  "properties": {
    "cluster": {
      "clusterSize": 4
    }
  },
  "tags": {}
}'
```

**Comment by ctaggart** [comment]
You need to be using the [Microsoft.AVS](https://review.docs.microsoft.com/en-us/rest/api/avs/?branch=avs) namespace. I recommend installing the [az vmware cli extension](https://github.com/Azure/az-vmware-cli) and then calling [az vmware private-cloud create](https://docs.microsoft.com/en-us/cli/azure/ext/vmware/vmware/private-cloud?view=azure-cli-latest) with `--debug` to see how to use the REST API.

**Comment by dw511214992** [comment]
Hi @ctaggart Cloud you please update the swagger? I think the namespace of swagger is still `Microsoft.VMwareVirtustream`.
Thank you

**Comment by ctaggart** [comment]
Make sure you are using:
specification\vmware\resource-manager\Microsoft.AVS\preview\2019-08-09-preview\vmware.json

instead of:
specification\vmwarevirtustream\resource-manager\Microsoft.VMwareVirtustream\preview\2019-08-09-preview\vmwarevirtustream.json

Yes, `networkBlock` is required and it is not reflected in this public preview API version. It is something I'm looking to address for the GA API version. The problem is we are reusing the same definition for the PATCH body and "Properties of a PATCH request body must not be required.".
