### ISSUE TITLE
Some issues in resource graph swaggers -- (related to https://github.com/Azure/azure-rest-api-specs/issues/9136)

### ISSUE THREAD

**Issue by dolauli** [Azure/azure-rest-api-specs#9466]
Part of the issues listed in https://github.com/Azure/azure-rest-api-specs/issues/9136 have not been fixed though the ticket has been closed.
List the details as below.
1. location can not be readonly in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview/graphquery.json#L272.
2. Following is the raw HTTP response when getting a specific query. Please see my comments start with //, which are issues not addressed.

```
{
  "properties": {
    "resultKind": "UnKnown",
    "timeModified": "2020-04-17T10:47:44.3813391Z",
    "query": "where isnotnull(tags['Prod']) and properties.extensions[0].Name == 'dockers'"
  },
  "type": "microsoft.resourcegraph/queries",
  "location": "global",
  "subscriptionId": "9e223dbe-3399-4e19-88eb-0975f02ac87f", // subscriptionId is missing in the swagger
  "resourceGroup": "testgroup", // resourceGroup is missing in the swagger
  "name": "sq01",
  "id": "/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/testgroup/providers/microsoft.resourcegraph/queries/sq01",
  "etag": "\"00003200-0000-1800-0000-5e9989500000\"" // it should be etag, but in swagger it is eTag. BTW, I think the value of "etag" should be "00003200-0000-1800-0000-5e9989500000"
} 
```

**Comment by dolauli** [comment]
Any updates on this issue?

**Comment by chiragg4u** [comment]
Thanks @dolauli for reporting this issue. We are looking at planning this work.

**Comment by snaheth** [comment]
Pending PR from @Yobretaw (attached from link above)

**Comment by Yobretaw** [comment]
@dolauli I believe the 1st issue (location readonly) has been fixed. For your comments in the 2nd item, a SavedQuery is actually a tracked resource which by definition has no subscriptionId/resourceGroup. We are mistakenly returning them in the current GET calls, and we'll be dropping those two fields shortly so that the response payload and swagger definition will be matching.

I'll fixing the etag casing in swagger. Regarding to the format (should have no double quotes inside), since it is not relevant to the swagger I've created a task on our side and will track it separately since it's not relevant to swagger.

**Comment by snaheth** [comment]
Closing this issue as @Yobretaw has addressed the issue above.

We are also rolling out an update soon to remove `subscriptionId` and `resourceGroup` from the response body for this endpoint. We're doing this because:

1. It ensures that our swagger and response body matches 1:1
2. Those two fields are implicit in the request ARM ID / Request URI
