### ISSUE TITLE
LogAnalytics.Solutions API failed to unmarshal response body

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#9672]
After tested, I found LogAnalytics.Solutions API failed to unmarshal response body and threw below error message when it failed to create solution.

Request body:
```
PUT https://management.azure.com/subscriptions/xx-xx-xx-xx/resourcegroups/acctestRG-01test2/providers/Microsoft.OperationsManagement/solutions/Containers(acctest-test012)


{
	"location": "westeurope",
	"plan": {
		"name": "Containers(acctest-test012)",
		"publisher": "Microsoft",
		"promotionCode": "",
		"product": "OMSGallery/AzureSQLAnalytics"
	},
	"properties": {
		"workspaceResourceId": "/subscriptions/xx-xx-xx-xx/resourcegroups/acctestrg-01test2/providers/microsoft.operationalinsights/workspaces/acctest-test012"
	}
}
```

Error message:
```
pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'F' looking for beginning of value
```

**Comment by ruowan** [comment]
@neil-yechenwei Is it a client issue? which client you used.

**Comment by neil-yechenwei** [comment]
@ruowan ，yes. I think so. We’re using azure go sdk as client.

**Comment by ruowan** [comment]
@ArcturusZhang Could you pls take a took at this go SDK issue?

**Comment by ArcturusZhang** [comment]
This seems like something is wrong in the async polling response, @neil-yechenwei could you please provide some log when the error was raised?

**Comment by neil-yechenwei** [comment]
@ArcturusZhang , after checked, I think the real error message is `For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)` and seems it failed to be unmarshalled in function `pt.initializeState()`.
![image](https://user-images.githubusercontent.com/19754191/83701361-01ffa080-a63c-11ea-92fc-cc0b0d302ccb.png)
![image](https://user-images.githubusercontent.com/19754191/83701381-0fb52600-a63c-11ea-900a-4e83620c0da6.png)

**Comment by ArcturusZhang** [comment]
@neil-yechenwei the error was thrown [here](https://github.com/Azure/go-autorest/blob/778ae565bde392f58e04c3c8ff07c2ac506d00c9/autorest/azure/async.go#L416)
`go-autorest` is expecting the error message to be a JSON string, but instead, the service returns the error message as a string literal
```
For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType. For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)
```
which is not a legal JSON string (legal JSON string should start with curly brace), therefore you will get the error message of `invalid character 'F' looking for beginning of value` complaining the first character is `F`.

This should be a service issue, in convention we are expecting that everything returned from the service should be a JSON string rather than plain string.
And particular in this case, this should be a shortage of the current swagger - it cannot describe the format of async errors.
